(() => {
  const S=window.TC,$=S.$;
  const revoke=u=>u&&URL.revokeObjectURL(u);
  const meta=f=>`${Math.round(f.size/1024)} KB · ${f.type||'image'}`;
  const load=file=>new Promise((resolve,reject)=>{ const url=URL.createObjectURL(file); const img=new Image(); img.onload=()=>resolve({img,url}); img.onerror=e=>{URL.revokeObjectURL(url); reject(e);}; img.src=url; });
  async function handleProfile(file){ if(!file) return; try{ const {img,url}=await load(file); revoke(S.sourceURL); S.sourceURL=url; S.sourceImage=img; $('thumb').src=url; $('sourceName').textContent=file.name; $('sourceMeta').textContent=meta(file); $('sourceCard').classList.remove('hidden'); $('cardEmpty').classList.add('hidden'); $('saveBtn').disabled=false; $('rescanBtn').disabled=false; $('printDate').value=S.today(); S.drawPreviews(); S.drawFront(); S.drawBack(); await S.scanProfile(); }catch(e){ console.error(e); S.toast('Could not open that profile screenshot.'); } }
  async function handleCode(file){ if(!file) return; try{ const {img,url}=await load(file); revoke(S.codeURL); S.codeURL=url; S.codeImage=img; $('codeThumb').src=url; $('codeSourceName').textContent=file.name; $('codeSourceMeta').textContent=meta(file); $('codeSourceCard').classList.remove('hidden'); $('codeEmpty').classList.add('hidden'); $('rescanCodeBtn').disabled=false; await S.scanCode(); }catch(e){ console.error(e); S.toast('Could not open that trainer code screenshot.'); } }
  $('profileInput').addEventListener('change',e=>handleProfile(e.target.files?.[0]||null));
  $('trainerCodeInput').addEventListener('change',e=>handleCode(e.target.files?.[0]||null));
  $('replaceBtn').addEventListener('click',()=>$('profileInput').click()); $('replaceCodeBtn').addEventListener('click',()=>$('trainerCodeInput').click()); $('rescanBtn').addEventListener('click',()=>S.scanProfile()); $('rescanCodeBtn').addEventListener('click',()=>S.scanCode()); $('retryTrainerBtn').addEventListener('click',()=>S.extractTrainerCutout()); $('retryBuddyBtn').addEventListener('click',()=>S.extractBuddyCutout()); $('resetBtn').addEventListener('click',()=>S.hardReset());
  document.querySelectorAll('.team').forEach(button=>button.addEventListener('click',()=>S.setTeam(button.dataset.team,false)));
  function syncRange(id,out,kind,key,fmt=v=>(+v).toFixed(2)){ const input=$(id), output=$(out); const update=()=>{ output.textContent=(id.includes('Zoom')?fmt(input.value)+'×':fmt(input.value)); S[kind][key]=+input.value; S.drawPreviews(); S.drawFront(); }; input.addEventListener('input',update); update(); }
  syncRange('tZoom','tZoomOut','trainerPose','zoom',v=>(+v).toFixed(2)); syncRange('tPanX','tPanXOut','trainerPose','x',v=>(+v).toFixed(2)); syncRange('tPanY','tPanYOut','trainerPose','y',v=>(+v).toFixed(2)); syncRange('bZoom','bZoomOut','buddyPose','zoom',v=>(+v).toFixed(2)); syncRange('bPanX','bPanXOut','buddyPose','x',v=>(+v).toFixed(2)); syncRange('bPanY','bPanYOut','buddyPose','y',v=>(+v).toFixed(2));
  ['trainerName','level','buddy','caught','stops','xp','startDate','printDate','trainerCode'].forEach(id=>$(id).addEventListener('input',()=>{ S.updateQuality(); S.drawFront(); S.drawBack(); })); $('trainerCode').addEventListener('blur',()=>{ $('trainerCode').value=S.formatCode($('trainerCode').value); S.drawBack(); });
  const flip=()=>{ S.showingBack=!S.showingBack; $('cardFlipper').classList.toggle('flipped',S.showingBack); $('sidePill').textContent=S.showingBack?'Back':'Front'; };
  $('flipBtn').addEventListener('click',flip); $('cardStage').addEventListener('click',flip); $('cardStage').addEventListener('keydown',e=>{ if(e.key==='Enter'||e.key===' '){ e.preventDefault(); flip(); } });
  $('saveBtn').addEventListener('click',()=>{ const canvas=S.showingBack?$('backCanvas'):$('cardCanvas'); const a=document.createElement('a'); a.href=canvas.toDataURL('image/png'); a.download=`trainer-card-${S.showingBack?'back':'front'}-${S.team}-v10.png`; a.click(); });
  $('printDate').value=S.today(); S.hardReset();
})();