const $=id=>document.getElementById(id);
const TEAM={valor:{name:'Valor',accent:'#ff4d55',asset:'assets/valor.svg'},mystic:{name:'Mystic',accent:'#30a5ff',asset:'assets/mystic.svg'},instinct:{name:'Instinct',accent:'#ffd534',asset:'assets/instinct.svg'}};
let sourceImage=null,sourceURL='',team='valor',scanning=false,ocrWorker=null,characterCrop=null,characterCutout=null,pokemonNames=null;
const fieldIds=['trainerName','level','buddy','caught','stops','xp','startDate'];
const allInputs=[...fieldIds,'printDate'];
const templates={};
Object.entries(TEAM).forEach(([k,v])=>{const i=new Image();i.src=v.asset;i.onload=drawCard;templates[k]=i});

function today(){return new Date().toLocaleDateString('en-US',{month:'numeric',day:'numeric',year:'numeric'})}
$('printDate').value=today();
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2400)}
function setState(id,s){const el=$(id+'State');if(!el)return;el.textContent=s==='ok'?'Detected':s==='review'?'Review':'Manual';el.className=s==='ok'?'ok':s==='review'?'review':''}
function updateQuality(){let ok=0;fieldIds.forEach(id=>{if($(id+'State')?.classList.contains('ok'))ok++});const q=Math.round(ok/fieldIds.length*100);$('qualityBar').style.width=q+'%';$('qualityText').textContent=q+'%'}
function setTeam(t,detected=false){if(!TEAM[t])return;team=t;document.body.dataset.team=t;document.querySelectorAll('.team').forEach(b=>b.classList.toggle('active',b.dataset.team===t));$('teamStatus').textContent=(detected?'Detected: ':'Selected: ')+TEAM[t].name;$('previewTeam').textContent=TEAM[t].name;drawCard()}
document.querySelectorAll('.team').forEach(b=>b.onclick=()=>setTeam(b.dataset.team,false));

function detectTeam(img){const c=document.createElement('canvas'),w=220,h=320;c.width=w;c.height=h;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(img,0,0,w,h);const d=x.getImageData(0,0,w,h).data;let R=0,B=0,Y=0;for(let i=0;i<d.length;i+=16){const r=d[i],g=d[i+1],b=d[i+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b);if(mx-mn<28)continue;R+=Math.max(0,r-(g+b)/2);B+=Math.max(0,b-(r+g)/2);Y+=Math.max(0,Math.min(r,g)-b*.75)}return Object.entries({valor:R,mystic:B,instinct:Y}).sort((a,b)=>b[1]-a[1])[0][0]}

function crop(img,x,y,w,h,scale=3,mode='normal'){
  const iw=img.naturalWidth||img.width,ih=img.naturalHeight||img.height;
  const c=document.createElement('canvas');c.width=Math.max(1,Math.round(iw*w*scale));c.height=Math.max(1,Math.round(ih*h*scale));
  const g=c.getContext('2d',{willReadFrequently:true});g.imageSmoothingEnabled=true;g.imageSmoothingQuality='high';g.drawImage(img,iw*x,ih*y,iw*w,ih*h,0,0,c.width,c.height);
  if(mode!=='normal'){const im=g.getImageData(0,0,c.width,c.height),d=im.data;for(let i=0;i<d.length;i+=4){const r=d[i],gg=d[i+1],b=d[i+2];let hit=false;if(mode==='red')hit=r>115&&r>gg*1.25&&r>b*1.2;if(mode==='green')hit=gg>80&&gg>r*1.15&&gg>b*.9;if(mode==='dark')hit=(r+gg+b)<390;const v=hit?0:255;d[i]=d[i+1]=d[i+2]=v;d[i+3]=255}g.putImageData(im,0,0)}return c
}
async function worker(){if(!ocrWorker){ocrWorker=await Tesseract.createWorker('eng',1,{logger:m=>{if(m.status==='recognizing text')$('scanPct').textContent=Math.round((m.progress||0)*100)+'%'}})}return ocrWorker}
async function read(c,psm='7',whitelist=''){const w=await worker();await w.setParameters({tessedit_pageseg_mode:psm,...(whitelist?{tessedit_char_whitelist:whitelist}:{})});const r=await w.recognize(c);return {text:r.data.text||'',confidence:r.data.confidence||0}}
const cleanNum=s=>(s.match(/[\d,]+/g)||[]).sort((a,b)=>b.length-a.length)[0]||'';
const cleanDate=s=>(s.match(/\b\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4}\b/)||[])[0]||'';
const norm=s=>s.toLowerCase().replace(/[^a-z0-9]/g,'');
function nameCandidates(text){return text.split(/\s+/).map(s=>s.replace(/[^A-Za-z0-9_-]/g,'')).filter(s=>s.length>=3&&s.length<=20&&!/^(me|friends|social|level|buddy|total|activity|today|week)$/i.test(s)&&!/^\d+$/.test(s))}
function pickTrainer(text){const a=nameCandidates(text);return a.find(s=>/[A-Za-z]/.test(s)&&/\d/.test(s))||a.find(s=>/[A-Z].*[a-z]|[a-z].*[A-Z]/.test(s))||a[0]||''}
function lev(a,b){a=norm(a);b=norm(b);const m=a.length,n=b.length,d=Array(n+1).fill(0).map((_,i)=>i);for(let i=1;i<=m;i++){let p=d[0];d[0]=i;for(let j=1;j<=n;j++){const t=d[j];d[j]=Math.min(d[j]+1,d[j-1]+1,p+(a[i-1]===b[j-1]?0:1));p=t}}return d[n]}
async function loadPokemonNames(){if(pokemonNames)return pokemonNames;try{const r=await fetch('https://pokeapi.co/api/v2/pokemon-species?limit=2000');const j=await r.json();pokemonNames=j.results.map(x=>x.name)}catch(e){pokemonNames=[]}return pokemonNames}
async function pickBuddy(text,trainer){let a=nameCandidates(text).filter(s=>norm(s)!==norm(trainer));const names=await loadPokemonNames();if(!names.length)return a[0]||'';let best=['',99];for(const c of a){for(const p of names){const dist=lev(c,p),score=dist/Math.max(c.length,p.length);if(score<best[1])best=[p,score]}}return best[1]<=.45?best[0].replace(/(^|-)(\w)/g,(_,p,c)=>p+c.toUpperCase()):(a[0]||'')}

async function scan(){if(!sourceImage||scanning)return;scanning=true;$('scanCard').classList.remove('hidden');$('scanTitle').textContent='Reading profile…';try{
  setTeam(detectTeam(sourceImage),true);
  const jobs=[['level','Level',crop(sourceImage,.035,.515,.20,.055,4,'red'),'0123456789'],['caught','Pokémon caught',crop(sourceImage,.55,.775,.42,.055,4,'green'),'0123456789,'],['stops','PokéStops visited',crop(sourceImage,.55,.815,.42,.055,4,'green'),'0123456789,'],['xp','Total XP',crop(sourceImage,.55,.855,.44,.055,4,'green'),'0123456789,'],['startDate','Start date',crop(sourceImage,.54,.895,.44,.06,4,'green'),'0123456789/-']];
  for(const [id,label,c,wlist] of jobs){$('scanDetail').textContent=label;const r=await read(c,'7',wlist);let v=id==='startDate'?cleanDate(r.text):cleanNum(r.text);if(id==='level'){const m=v.match(/\d{1,3}/);v=m&&+m[0]<=100?m[0]:''}if(v){$(id).value=v;setState(id,r.confidence>=55?'ok':'review')}else setState(id,'review')}
  $('scanDetail').textContent='Trainer name';const idA=crop(sourceImage,.00,.055,.64,.18,3,'normal'),idB=crop(sourceImage,.00,.055,.64,.18,4,'red');const [ra,rb]=await Promise.all([read(idA,'6'),read(idB,'6')]);const trainer=pickTrainer(ra.text+'\n'+rb.text);if(trainer){$('trainerName').value=trainer;setState('trainerName','ok')}else setState('trainerName','review');
  $('scanDetail').textContent='Buddy name';const bA=crop(sourceImage,.10,.125,.42,.10,4,'normal'),bB=crop(sourceImage,.10,.125,.42,.10,4,'red');const [rba,rbb]=await Promise.all([read(bA,'6'),read(bB,'6')]);const buddy=await pickBuddy(rba.text+'\n'+rbb.text,trainer);if(buddy){$('buddy').value=buddy;setState('buddy','ok')}else setState('buddy','review');
  updateQuality();toast('Profile scan complete — review anything marked Review.');
 }catch(e){console.error(e);toast('OCR had trouble. You can still edit every field.')}finally{scanning=false;$('scanCard').classList.add('hidden');drawCard()}}

function makeCharacterCrop(img){const iw=img.naturalWidth,ih=img.naturalHeight;const c=document.createElement('canvas');const sx=iw*.30,sy=ih*.055,sw=iw*.69,sh=ih*.54;c.width=Math.round(sw);c.height=Math.round(sh);c.getContext('2d').drawImage(img,sx,sy,sw,sh,0,0,c.width,c.height);characterCrop=c;characterCutout=null;$('portraitEmpty').classList.add('hidden');$('retryExtractBtn').disabled=false;drawPortrait();drawCard();extractCutout()}
async function extractCutout(){if(!characterCrop||!window.removeProfileBackground)return;$('extractStatus').textContent='Extracting…';try{const blob=await new Promise(r=>characterCrop.toBlob(r,'image/png'));const out=await window.removeProfileBackground(blob);const url=URL.createObjectURL(out),im=new Image();await new Promise((res,rej)=>{im.onload=res;im.onerror=rej;im.src=url});characterCutout=im;$('extractStatus').textContent='Cutout ready';$('extractHelp').textContent='Transparent trainer + buddy layer created from the uploaded screenshot.';drawPortrait();drawCard()}catch(e){console.warn(e);$('extractStatus').textContent='Full crop';$('extractHelp').textContent='Automatic cutout failed; the complete trainer + buddy crop is preserved instead.';drawPortrait();drawCard()}}
function dims(i){return {w:i.naturalWidth||i.width,h:i.naturalHeight||i.height}}
function contain(ctx,img,x,y,w,h,z=1,px=0,py=0){const d=dims(img);if(!d.w)return;const s=Math.min(w/d.w,h/d.h)*z,nw=d.w*s,nh=d.h*s;ctx.drawImage(img,x+(w-nw)/2+px*w*.15,y+(h-nh)/2+py*h*.15,nw,nh)}
function drawPortrait(){const c=$('portraitCanvas'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);const gr=g.createLinearGradient(0,0,0,c.height);gr.addColorStop(0,'#111923');gr.addColorStop(1,'#080b10');g.fillStyle=gr;g.fillRect(0,0,c.width,c.height);const img=characterCutout||characterCrop;if(img)contain(g,img,20,18,c.width-40,c.height-36,+$('zoom').value,+$('panX').value,+$('panY').value)}
function centerText(g,text,x,y,max,size=13){if(!text)return;g.textAlign='center';g.textBaseline='middle';g.fillStyle='#fff';g.shadowColor='rgba(0,0,0,.85)';g.shadowBlur=4;let s=size;do{g.font=`700 ${s}px system-ui`;if(g.measureText(text).width<=max)break;s-=.5}while(s>8);g.fillText(text,x,y,max);g.shadowBlur=0}
function drawCard(){const c=$('cardCanvas'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);g.save();g.scale(2,2);g.fillStyle='#0a0d14';g.fillRect(0,0,458,1145);const t=templates[team];if(t?.complete)g.drawImage(t,0,0,458,1145);const img=characterCutout||characterCrop;if(img){g.save();g.beginPath();g.roundRect(54,150,350,560,18);g.clip();if(!characterCutout){g.fillStyle=team==='valor'?'rgba(55,5,12,.45)':team==='mystic'?'rgba(2,23,52,.45)':'rgba(55,43,0,.45)';g.fillRect(54,150,350,560);g.globalAlpha=.92}contain(g,img,58,155,342,550,+$('zoom').value,+$('panX').value,+$('panY').value);g.restore()}
  const v={trainerName:[229,776,350,14],level:[93,837,95,13],buddy:[294,837,225,13],caught:[96,911,105,12],stops:[229,911,105,12],xp:[362,911,105,12],startDate:[129,984,155,12],printDate:[329,984,155,12]};for(const [id,a] of Object.entries(v))centerText(g,$(id).value.trim(),...a);g.restore()}

function loadFile(file){if(!file)return;if(sourceURL)URL.revokeObjectURL(sourceURL);sourceURL=URL.createObjectURL(file);const im=new Image();im.onload=()=>{sourceImage=im;$('thumb').src=sourceURL;$('sourceName').textContent=file.name;$('sourceMeta').textContent=`${im.naturalWidth} × ${im.naturalHeight} · ${(file.size/1048576).toFixed(1)} MB`;$('sourceCard').classList.remove('hidden');$('saveBtn').disabled=false;$('rescanBtn').disabled=false;$('cardEmpty').classList.add('hidden');setTeam(detectTeam(im),true);makeCharacterCrop(im);scan()};im.src=sourceURL}
$('profileInput').onchange=e=>loadFile(e.target.files?.[0]);$('replaceBtn').onclick=()=>$('profileInput').click();$('rescanBtn').onclick=scan;$('retryExtractBtn').onclick=extractCutout;
allInputs.forEach(id=>$(id).addEventListener('input',()=>{if(fieldIds.includes(id))setState(id,'manual');updateQuality();drawCard()}));['zoom','panX','panY'].forEach(id=>$(id).addEventListener('input',()=>{$(id+'Out').textContent=id==='zoom'?(+$('zoom').value).toFixed(2)+'×':(+$(id).value).toFixed(2);drawPortrait();drawCard()}));
$('saveBtn').onclick=()=>{drawCard();const a=document.createElement('a');a.download=`${($('trainerName').value||'trainer').replace(/\W+/g,'_')}_${team}_trainer_card.png`;a.href=$('cardCanvas').toDataURL('image/png');a.click();toast('High-resolution card saved.')};
$('resetBtn').onclick=()=>{if(sourceURL)URL.revokeObjectURL(sourceURL);sourceImage=null;sourceURL='';characterCrop=characterCutout=null;$('profileInput').value='';$('sourceCard').classList.add('hidden');$('saveBtn').disabled=true;$('rescanBtn').disabled=true;$('retryExtractBtn').disabled=true;$('cardEmpty').classList.remove('hidden');$('portraitEmpty').classList.remove('hidden');allInputs.forEach(id=>$(id).value=id==='printDate'?today():'');fieldIds.forEach(id=>setState(id,'manual'));document.body.dataset.team='neutral';document.querySelectorAll('.team').forEach(b=>b.classList.remove('active'));$('teamStatus').textContent='Waiting for upload';$('previewTeam').textContent='Choose a team';updateQuality();drawPortrait();drawCard()};
if('serviceWorker'in navigator&&location.protocol==='https:')addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
setTeam('valor');document.body.dataset.team='neutral';document.querySelectorAll('.team').forEach(b=>b.classList.remove('active'));$('teamStatus').textContent='Waiting for upload';$('previewTeam').textContent='Choose a team';drawPortrait();drawCard();
