(() => {
  const S=window.TC,$=S.$;
  const W=600,H=800,SCALE=2;
  const palette={valor:{accent:'#ff315d',glow:'#ffb08a',pale:'#fff2e7'},mystic:{accent:'#2ab4ff',glow:'#b9f4ff',pale:'#f2fdff'},instinct:{accent:'#ffd21f',glow:'#fff49a',pale:'#fffbe8'}};
  const TERRAIN_Y={valor:665,mystic:665,instinct:664};
  const backgrounds={},contactCache=new WeakMap();
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));

  function loadLockedBackground(team){fetch(`assets/locked/${team}.b64?v=24`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`missing ${team}`);return r.text();}).then(b64=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src='data:image/avif;base64,'+b64.trim();})).then(img=>{backgrounds[team]=img;S.drawFront?.();S.drawBack?.();}).catch(()=>{const img=new Image();img.onload=()=>{backgrounds[team]=img;S.drawFront?.();S.drawBack?.();};img.src=`assets/${team}-bg.svg?v=24`;});}
  ['valor','mystic','instinct'].forEach(loadLockedBackground);

  function panelPath(g,x,y,w,h,cut=14){g.beginPath();g.moveTo(x+cut,y);g.lineTo(x+w-cut,y);g.lineTo(x+w,y+cut);g.lineTo(x+w,y+h-cut);g.lineTo(x+w-cut,y+h);g.lineTo(x+cut,y+h);g.lineTo(x,y+h-cut);g.lineTo(x,y+cut);g.closePath();}
  function fitText(g,text,x,y,max,size,weight=900,align='center'){if(!text)return;let s=size;g.textAlign=align;g.textBaseline='middle';while(s>9){g.font=`${weight} ${s}px system-ui,-apple-system,Segoe UI,sans-serif`;if(g.measureText(text).width<=max)break;s--;}g.fillText(text,x,y,max);}
  function bottomFit(g,img,cx,bottom,maxW,maxH,zoom=1,dx=0,dy=0){const iw=img?.naturalWidth||img?.width||0,ih=img?.naturalHeight||img?.height||0;if(!iw||!ih)return;const scale=Math.min(maxW/iw,maxH/ih)*zoom,nw=iw*scale,nh=ih*scale;g.drawImage(img,cx-nw/2+dx,bottom-nh+dy,nw,nh);}

  function estimateContactFrac(img,role='trainer'){
    if(!img)return .98;let cached=contactCache.get(img);if(cached?.[role])return cached[role];
    const iw=img.naturalWidth||img.width||0,ih=img.naturalHeight||img.height||0;if(!iw||!ih)return .98;
    const max=260,s=Math.min(1,max/Math.max(iw,ih)),w=Math.max(32,Math.round(iw*s)),h=Math.max(32,Math.round(ih*s));
    const c=document.createElement('canvas');c.width=w;c.height=h;const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(img,0,0,w,h);let d;try{d=g.getImageData(0,0,w,h).data;}catch{return .98;}
    const x0=Math.floor(w*(role==='buddy'?.08:.14)),x1=Math.ceil(w*(role==='buddy'?.72:.86)),bottoms=[];
    for(let x=x0;x<x1;x++){let yFound=-1;for(let y=h-1;y>=Math.floor(h*.45);y--){if(d[(y*w+x)*4+3]>42){yFound=y;break;}}if(yFound>=Math.floor(h*.55))bottoms.push(yFound);}
    let frac=.98;if(bottoms.length>8){bottoms.sort((a,b)=>a-b);const q=role==='buddy'?.88:.95;frac=bottoms[Math.min(bottoms.length-1,Math.floor((bottoms.length-1)*q))]/h;frac=clamp(frac,.72,.995);}
    cached=cached||{};cached[role]=frac;contactCache.set(img,cached);return frac;
  }
  function contactFit(g,img,cx,contactY,maxW,maxH,zoom=1,dx=0,dy=0,role='trainer'){const iw=img?.naturalWidth||img?.width||0,ih=img?.naturalHeight||img?.height||0;if(!iw||!ih)return;const scale=Math.min(maxW/iw,maxH/ih)*zoom,nw=iw*scale,nh=ih*scale,frac=estimateContactFrac(img,role);g.drawImage(img,cx-nw/2+dx,contactY-frac*nh+dy,nw,nh);}

  function drawBackground(g,team){const bg=backgrounds[team],scene=S.scene||{},z=clamp(Number(scene.bgZoom)||1,1,1.16),py=clamp(Number(scene.bgY)||0,-70,70);if(bg?.complete&&(bg.naturalWidth||bg.width)){g.drawImage(bg,0,0,W,H);if(Math.abs(py)>.1||Math.abs(z-1)>.001){g.save();g.beginPath();g.rect(12,14,576,658);g.clip();const dw=W*z,dh=H*z,dx=(W-dw)/2,dy=(H-dh)/2+py;g.drawImage(bg,dx,dy,dw,dh);g.restore();}return;}const p=palette[team]||palette.valor,gr=g.createLinearGradient(0,0,0,H);gr.addColorStop(0,'#12131a');gr.addColorStop(.5,p.accent+'66');gr.addColorStop(1,'#030407');g.fillStyle=gr;g.fillRect(0,0,W,H);}
  function drawAnimatedEffect(g,team){const p=palette[team]||palette.valor,t=S.animPhase||0;g.save();if(team==='valor'){for(let i=0;i<26;i++){const seed=((i*37)%97)/97,x=34+((i*83)%532),y=690-((t+seed)%1)*525,r=1+((i*11)%8)*.22;g.globalAlpha=.18+.58*(1-((t+seed)%1));g.fillStyle=i%3?p.glow:p.accent;g.beginPath();g.arc(x,y,r,0,Math.PI*2);g.fill();}}else if(team==='mystic'){for(let i=0;i<24;i++){const seed=((i*29)%89)/89,x=35+((i*71)%530),y=115+((t*.55+seed)%1)*520;g.globalAlpha=.18+.34*(.5+.5*Math.sin((t+seed)*Math.PI*2));g.fillStyle=p.pale;g.beginPath();g.arc(x,y,1+((i*7)%5)*.32,0,Math.PI*2);g.fill();}g.globalAlpha=.09;g.strokeStyle=p.glow;g.lineWidth=9;g.beginPath();g.moveTo(-40,550+Math.sin(t*Math.PI*2)*13);g.bezierCurveTo(150,500,400,620,650,530);g.stroke();}else{const flash=Math.sin(t*Math.PI*12);if(flash>.58||flash<-.82){g.globalAlpha=.55;g.strokeStyle=p.glow;g.lineWidth=2.2;const bolts=[[[35,160],[72,205],[53,235],[92,278]],[[565,194],[530,226],[548,259],[510,301]],[[61,525],[95,553],[77,582],[112,612]]];for(const pts of bolts){g.beginPath();g.moveTo(...pts[0]);pts.slice(1).forEach(q=>g.lineTo(...q));g.stroke();}}}g.restore();}
  function drawHeader(g,team){const p=palette[team]||palette.valor,name=($('trainerName').value||'TRAINER').trim();g.fillStyle=p.pale;g.textAlign='left';g.textBaseline='middle';g.font='750 8.5px system-ui';g.fillText('TRAINER',34,38);g.fillText('CARD',34,50);const ng=g.createLinearGradient(125,22,515,92);ng.addColorStop(0,p.pale);ng.addColorStop(.58,'#fff');ng.addColorStop(1,p.accent);g.fillStyle=ng;g.shadowColor='rgba(0,0,0,.55)';g.shadowBlur=7;fitText(g,name,330,58,400,45,950);g.shadowBlur=0;g.fillStyle=p.pale;g.font='800 14px system-ui';g.textAlign='right';g.fillText('Lv.',228,111);g.fillStyle='#fff';fitText(g,($('level').value||'—').trim(),278,110,82,31,950);g.fillStyle=p.pale;g.font='800 11px system-ui';g.textAlign='left';g.fillText('Buddy:',338,103);g.fillStyle='#fff';fitText(g,($('buddy').value||'—').trim(),338,122,205,18,900,'left');}
  function shadow(g,cx,y,w,alpha=.38){g.save();const gr=g.createRadialGradient(cx,y,5,cx,y,w);gr.addColorStop(0,`rgba(0,0,0,${alpha})`);gr.addColorStop(.55,`rgba(0,0,0,${alpha*.48})`);gr.addColorStop(1,'rgba(0,0,0,0)');g.fillStyle=gr;g.beginPath();g.ellipse(cx,y,w,Math.max(7,w*.09),0,0,Math.PI*2);g.fill();g.restore();}

  function drawSubjects(g,team){const scene=S.scene||{},terrain=TERRAIN_Y[team]??665,groundY=clamp(Number(scene.groundY)||terrain,630,680),buddyMode=scene.buddyMode==='float'?'float':'ground',floatH=clamp(Number(scene.buddyFloat)||90,20,200),tp=S.trainerPose||{zoom:1,x:0,y:0},bp=S.buddyPose||{zoom:1,x:0,y:0};g.save();panelPath(g,22,128,556,552,18);g.clip();const trainerGround=groundY,buddyGround=buddyMode==='float'?groundY-floatH:groundY-8;if(S.trainerCutout)shadow(g,407,trainerGround+2,72,.44);if(S.buddyCutout)shadow(g,217,groundY+1,buddyMode==='float'?58:96,buddyMode==='float'?.16:.31);if(S.buddyCutout)contactFit(g,S.buddyCutout,217,buddyGround,390,500,1.04*(bp.zoom||1),-7+(bp.x||0)*62,(bp.y||0)*38,'buddy');if(S.trainerCutout)contactFit(g,S.trainerCutout,407,trainerGround,292,420,1.04*(tp.zoom||1),5+(tp.x||0)*52,(tp.y||0)*36,'trainer');g.restore();}
  function statBlock(g,label,value,cx,team){const p=palette[team]||palette.valor;g.textAlign='center';g.textBaseline='middle';g.fillStyle=p.pale;g.font='800 7.5px system-ui';g.fillText(label,cx,699);g.fillStyle='#fff';fitText(g,value||'—',cx,728,155,20,950);}
  function drawStats(g,team){statBlock(g,'POKÉMON CAUGHT',($('caught').value||'').trim(),118,team);statBlock(g,'POKÉSTOPS VISITED',($('stops').value||'').trim(),300,team);statBlock(g,'TOTAL XP',($('xp').value||'').trim(),482,team);const p=palette[team]||palette.valor;g.fillStyle=p.pale;g.font='650 6.6px system-ui';g.textBaseline='middle';g.textAlign='left';g.fillText(`START  ${($('startDate').value||'—').trim()}`,42,765);g.textAlign='center';g.fillText(`PRINT DATE  ${($('printDate').value||'—').trim()}`,300,782);}

  S.drawFront=()=>{const c=$('cardCanvas');if(!c)return;if(c.width!==W*SCALE||c.height!==H*SCALE){c.width=W*SCALE;c.height=H*SCALE;}const g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);g.save();g.scale(SCALE,SCALE);const team=S.team||'valor';drawBackground(g,team);drawAnimatedEffect(g,team);drawHeader(g,team);drawSubjects(g,team);drawStats(g,team);g.restore();};
  S.drawBack=()=>{const c=$('backCanvas');if(!c)return;if(c.width!==W*SCALE||c.height!==H*SCALE){c.width=W*SCALE;c.height=H*SCALE;}const g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);g.save();g.scale(SCALE,SCALE);const team=S.team||'valor',p=palette[team]||palette.valor,cfg=S.TEAM[team];drawBackground(g,team);drawAnimatedEffect(g,team);g.textAlign='center';g.textBaseline='middle';g.fillStyle='#fff';fitText(g,($('trainerName').value||'TRAINER').trim(),300,82,460,35,950);g.fillStyle=p.pale;g.font='900 13px system-ui';g.fillText((cfg?.name||team).toUpperCase(),300,119);g.fillStyle='rgba(4,6,10,.72)';g.strokeStyle=p.glow;g.lineWidth=1.5;panelPath(g,90,165,420,455,20);g.fill();g.stroke();g.fillStyle='#fff';panelPath(g,157,212,286,286,16);g.fill();if(S.qrCrop)bottomFit(g,S.qrCrop,300,481,252,252,1,0,0);else{g.fillStyle='#151922';g.font='800 13px system-ui';g.fillText('UPLOAD QR IMAGE',300,353);g.fillStyle='#657080';g.font='600 9px system-ui';g.fillText('Your QR image appears here',300,375);}g.fillStyle='#fff';fitText(g,S.formatCode($('trainerCode').value)||'••••  ••••  ••••',300,546,360,24,950);g.fillStyle=p.pale;g.font='800 8px system-ui';g.fillText('TRAINER CODE',300,575);g.fillStyle='rgba(4,6,10,.72)';panelPath(g,90,645,420,82,16);g.fill();g.textAlign='left';g.fillStyle=p.pale;g.font='700 7.5px system-ui';g.fillText('LEVEL',118,665);g.fillText('BUDDY',252,665);g.fillText('TEAM',420,665);g.fillStyle='#fff';g.font='900 16px system-ui';g.fillText(($('level').value||'—').trim(),118,697);fitText(g,($('buddy').value||'—').trim(),252,697,135,16,900,'left');g.fillStyle=p.glow;g.fillText(cfg?.name||team,420,697);g.fillStyle=p.pale;g.font='650 6.6px system-ui';g.textAlign='center';g.fillText(`PRINT DATE  ${($('printDate').value||'—').trim()}`,300,779);g.restore();};
})();