(() => {
'use strict';
const $=id=>document.getElementById(id);
const TEAM={valor:{name:'Valor',hue:354},mystic:{name:'Mystic',hue:205},instinct:{name:'Instinct',hue:48}};
const S={team:'valor',hue:354,infoImage:null,infoURL:'',trainerSource:null,trainerURL:'',buddySource:null,buddyURL:'',trainerCrop:{cx:.5,cy:.42,size:.62},buddyCrop:{cx:.5,cy:.42,r:.31},trainerCanvas:null,buddyCanvas:null,codeImage:null,codeURL:'',qrCrop:null,ocr:null,scanning:false,showBack:false,drag:null};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const toast=msg=>{const t=$('toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),2400);};
const today=()=>new Date().toLocaleDateString('en-US',{month:'numeric',day:'numeric',year:'numeric'});
const revoke=u=>{if(u)URL.revokeObjectURL(u);};
const loadFile=file=>new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>resolve({img,url});img.onerror=e=>{URL.revokeObjectURL(url);reject(e);};img.src=url;});
const meta=f=>`${Math.round(f.size/1024)} KB · ${f.type||'image'}`;
const norm=s=>(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');
const fmtNum=d=>d.replace(/\B(?=(\d{3})+(?!\d))/g,',');
const cleanDate=t=>(t.match(/\b\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4}\b/)||[])[0]||'';
function setState(id,state){const e=$(id+'State');if(!e)return;e.textContent=state==='ok'?'Detected':state==='review'?'Review':'Manual';e.className=state==='ok'?'ok':state==='review'?'review':'';}
function updateQuality(){const ids=['trainerName','level','buddy','caught','stops','xp','startDate'];const n=ids.filter(id=>($(id)?.value||'').trim()).length;$('qualityText').textContent=`${Math.round(n/ids.length*100)}%`;}
function setTheme(){const h=TEAM[S.team].hue;S.hue=h;document.documentElement.style.setProperty('--accent',`hsl(${h} 82% 58%)`);document.documentElement.style.setProperty('--accent2',`hsl(${(h+18)%360} 78% 72%)`);}
function setTeam(team,detected=false){if(!TEAM[team])return;S.team=team;setTheme();document.querySelectorAll('.team').forEach(b=>b.classList.toggle('active',b.dataset.team===team));$('teamStatus').textContent=`${detected?'Detected':'Selected'}: ${TEAM[team].name}`;$('previewTeam').textContent=TEAM[team].name;drawAll();}
function detectTeam(img){const c=document.createElement('canvas');c.width=220;c.height=330;const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(img,0,0,c.width,c.height);const d=g.getImageData(0,0,c.width,c.height).data;let R=0,B=0,Y=0;for(let i=0;i<d.length;i+=20){const r=d[i],gg=d[i+1],b=d[i+2],mx=Math.max(r,gg,b),mn=Math.min(r,gg,b);if(mx-mn<22)continue;R+=Math.max(0,r-(gg+b)/2);B+=Math.max(0,b-(r+gg)/2);Y+=Math.max(0,Math.min(r,gg)-b*.72);}return Object.entries({valor:R,mystic:B,instinct:Y}).sort((a,b)=>b[1]-a[1])[0][0];}
async function worker(){if(!S.ocr)S.ocr=await Tesseract.createWorker('eng',1,{logger:m=>{if(m.status==='recognizing text'&&$('scanPct'))$('scanPct').textContent=`${Math.round((m.progress||0)*100)}%`;}});return S.ocr;}
async function read(c,psm='7',whitelist=''){const w=await worker();await w.setParameters({tessedit_pageseg_mode:psm,...(whitelist?{tessedit_char_whitelist:whitelist}:{})});const r=await w.recognize(c);return{text:r.data.text||'',confidence:r.data.confidence||0};}
function ocrCrop(img,x,y,w,h,scale=7,mode='normal'){const iw=img.naturalWidth||img.width,ih=img.naturalHeight||img.height,c=document.createElement('canvas');c.width=Math.max(1,Math.round(iw*w*scale));c.height=Math.max(1,Math.round(ih*h*scale));const g=c.getContext('2d',{willReadFrequently:true});g.imageSmoothingEnabled=true;g.imageSmoothingQuality='high';g.drawImage(img,iw*x,ih*y,iw*w,ih*h,0,0,c.width,c.height);if(mode!=='normal'){const im=g.getImageData(0,0,c.width,c.height),d=im.data;for(let i=0;i<d.length;i+=4){const r=d[i],gg=d[i+1],b=d[i+2];let hit=false;if(mode==='maroon')hit=r>72&&r>gg*1.16&&r>b*1.06&&gg<190;if(mode==='green')hit=gg>82&&gg>r*1.03&&gg>b*.86;if(mode==='red')hit=r>92&&r>gg*1.10&&r>b*1.02;if(mode==='dark')hit=(r+gg+b)<440;const v=hit?0:255;d[i]=d[i+1]=d[i+2]=v;d[i+3]=255;}g.putImageData(im,0,0);}return c;}
function textTokens(text,allowDigits=true){const out=[];for(const line of (text||'').split(/[\r\n]+/)){const compact=line.replace(allowDigits?/[^A-Za-z0-9_-]/g:/[^A-Za-z-]/g,'').replace(/^[_-]+|[_-]+$/g,'');if(compact.length>=2&&compact.length<=28)out.push(compact);const re=allowDigits?/[A-Za-z][A-Za-z0-9_-]{1,27}/g:/[A-Za-z][A-Za-z-]{1,27}/g;out.push(...(line.match(re)||[]));}return[...new Set(out.filter(Boolean))];}
function literalConsensus(reads,{allowDigits=true,blocked=[]}={}){const stop=new Set(blocked.map(norm)),groups=new Map();for(const r of reads){for(const t of textTokens(r.text,allowDigits)){const k=norm(t);if(!k||stop.has(k)||/^\d+$/.test(t))continue;const g=groups.get(k)||{value:t,count:0,total:0,max:0};g.count++;g.total+=Number(r.confidence||0);g.max=Math.max(g.max,Number(r.confidence||0));if(t.length>g.value.length)g.value=t;groups.set(k,g);}}let best=null;for(const g of groups.values()){g.avg=g.total/g.count;g.score=g.count*70+g.avg+Math.min(g.value.length,18);if(!best||g.score>best.score)best=g;}return best||{value:'',count:0,max:0};}
function numberFrom(text){const ms=(text||'').match(/[\d][\d,\.\s]*/g)||[],ds=ms.map(s=>s.replace(/\D/g,'')).filter(Boolean);return ds.sort((a,b)=>b.length-a.length)[0]||'';}
function consensusNumber(reads,{minDigits=1,maxDigits=12,maxValue=Number.MAX_SAFE_INTEGER}={}){const m=new Map();for(const r of reads){const d=numberFrom(r.text);if(!d||d.length<minDigits||d.length>maxDigits||Number(d)>maxValue)continue;const v=m.get(d)||{digits:d,count:0,confidence:0};v.count++;v.confidence=Math.max(v.confidence,r.confidence||0);m.set(d,v);}return[...m.values()].sort((a,b)=>b.count-a.count||b.confidence-a.confidence)[0]||null;}
function consensusDate(reads){const m=new Map();for(const r of reads){const d=cleanDate(r.text);if(!d)continue;const v=m.get(d)||{value:d,count:0,confidence:0};v.count++;v.confidence=Math.max(v.confidence,r.confidence||0);m.set(d,v);}return[...m.values()].sort((a,b)=>b.count-a.count||b.confidence-a.confidence)[0]||null;}
async function readSet(normal,masked,whitelist){return[await read(normal,'7',whitelist),await read(masked,'7',whitelist),await read(normal,'6',whitelist),await read(masked,'13',whitelist)];}
async function scanInfo(){if(!S.infoImage||S.scanning)return;S.scanning=true;$('scanCard').classList.remove('hidden');$('scanPct').textContent='0%';try{setTeam(detectTeam(S.infoImage),true);$('scanTitle').textContent='Reading information screenshot';let normal,mask,reads,pick;$('scanDetail').textContent='Trainer name';normal=ocrCrop(S.infoImage,.045,.126,.40,.038,7);mask=ocrCrop(S.infoImage,.045,.126,.40,.038,7,'maroon');reads=await readSet(normal,mask,'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-');pick=literalConsensus(reads,{allowDigits:true,blocked:['me','friends','social','level','buddy','history','scrapbook','journal','style','total','activity']});if(pick.value){$('trainerName').value=pick.value;setState('trainerName',pick.count>=2||pick.max>=72?'ok':'review');}else setState('trainerName','review');$('scanDetail').textContent='Buddy name';normal=ocrCrop(S.infoImage,.045,.151,.40,.036,8);mask=ocrCrop(S.infoImage,.045,.151,.40,.036,8,'maroon');reads=await readSet(normal,mask,'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-');pick=literalConsensus(reads,{allowDigits:false,blocked:['buddy','history','scrapbook','journal','style','friends','social','me','mega','cp',$('trainerName').value]});if(pick.value){$('buddy').value=pick.value;setState('buddy',pick.count>=2||pick.max>=72?'ok':'review');}else setState('buddy','review');const jobs=[['level','Level',[.055,.526,.16,.050],'red','0123456789',{minDigits:1,maxDigits:3,maxValue:100}],['caught','Pokémon caught',[.585,.792,.30,.035],'green','0123456789,',{minDigits:2,maxDigits:9}],['stops','PokéStops visited',[.585,.831,.30,.035],'green','0123456789,',{minDigits:2,maxDigits:9}],['xp','Total XP',[.585,.870,.36,.035],'green','0123456789,',{minDigits:4,maxDigits:12}],['startDate','Start date',[.585,.909,.30,.035],'green','0123456789/-',null]];for(const[id,label,r,mode,white,rules]of jobs){$('scanDetail').textContent=label;normal=ocrCrop(S.infoImage,...r,6);mask=ocrCrop(S.infoImage,...r,6,mode);reads=await readSet(normal,mask,white);if(id==='startDate'){const p=consensusDate(reads);if(p){$(id).value=p.value;setState(id,p.count>=2?'ok':'review');}else setState(id,'review');}else{const p=consensusNumber(reads,rules||{});if(p){$(id).value=id==='level'?String(Number(p.digits)):fmtNum(p.digits);setState(id,p.count>=2?'ok':'review');}else setState(id,'review');}}updateQuality();drawAll();toast('OCR filled what it could. Review anything marked Review.');}catch(e){console.error(e);toast('OCR could not finish. The fields can still be entered manually.');}finally{S.scanning=false;$('scanCard').classList.add('hidden');}}
function setupCropCanvas(kind){const c=$(kind+'CropCanvas'),src=S[kind+'Source'];if(!c||!src)return;const maxW=Math.min(900,src.naturalWidth||src.width),ratio=(src.naturalHeight||src.height)/(src.naturalWidth||src.width);c.width=Math.round(maxW);c.height=Math.round(maxW*ratio);drawCropEditor(kind);}
function cropPixels(kind){const c=$(kind+'CropCanvas'),src=S[kind+'Source'];if(!c||!src)return null;const iw=src.naturalWidth||src.width,ih=src.naturalHeight||src.height;if(kind==='trainer'){const s=S.trainerCrop,side=s.size*Math.min(iw,ih),cx=s.cx*iw,cy=s.cy*ih;return{x:clamp(cx-side/2,0,iw-side),y:clamp(cy-side/2,0,ih-side),w:side,h:side};}const s=S.buddyCrop,r=s.r*Math.min(iw,ih),cx=s.cx*iw,cy=s.cy*ih;return{x:clamp(cx-r,0,iw-2*r),y:clamp(cy-r,0,ih-2*r),w:2*r,h:2*r};}
function drawCropEditor(kind){const c=$(kind+'CropCanvas'),src=S[kind+'Source'];if(!c||!src)return;const g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);g.drawImage(src,0,0,c.width,c.height);g.fillStyle='rgba(0,0,0,.48)';g.fillRect(0,0,c.width,c.height);const min=Math.min(c.width,c.height);g.save();if(kind==='trainer'){const s=S.trainerCrop,side=s.size*min,x=s.cx*c.width-side/2,y=s.cy*c.height-side/2;g.beginPath();g.rect(x,y,side,side);g.clip();g.drawImage(src,0,0,c.width,c.height);g.restore();g.strokeStyle='#fff';g.lineWidth=Math.max(3,c.width/250);g.strokeRect(x,y,side,side);const hs=Math.max(13,c.width/55);g.fillStyle='#fff';g.fillRect(x+side-hs/2,y+side-hs/2,hs,hs);g.fillStyle='#fff';g.font=`900 ${Math.max(14,c.width/42)}px system-ui`;g.fillText('TRAINER SQUARE',x+9,y+Math.max(22,c.width/30));}else{const s=S.buddyCrop,r=s.r*min,cx=s.cx*c.width,cy=s.cy*c.height;g.beginPath();g.arc(cx,cy,r,0,Math.PI*2);g.clip();g.drawImage(src,0,0,c.width,c.height);g.restore();g.strokeStyle='#fff';g.lineWidth=Math.max(3,c.width/250);g.beginPath();g.arc(cx,cy,r,0,Math.PI*2);g.stroke();const hs=Math.max(13,c.width/55);g.fillStyle='#fff';g.beginPath();g.arc(cx+r,cy,hs*.6,0,Math.PI*2);g.fill();g.fillStyle='#fff';g.font=`900 ${Math.max(14,c.width/42)}px system-ui`;g.fillText('BUDDY CIRCLE',cx-r+9,cy-r+Math.max(22,c.width/30));}}
function applyCrop(kind){const src=S[kind+'Source'];if(!src)return;const p=cropPixels(kind);if(!p)return;const out=document.createElement('canvas'),size=700;out.width=size;out.height=size;const g=out.getContext('2d');g.imageSmoothingEnabled=true;g.imageSmoothingQuality='high';if(kind==='buddy'){g.save();g.beginPath();g.arc(size/2,size/2,size/2,0,Math.PI*2);g.clip();g.drawImage(src,p.x,p.y,p.w,p.h,0,0,size,size);g.restore();}else g.drawImage(src,p.x,p.y,p.w,p.h,0,0,size,size);S[kind+'Canvas']=out;const img=$(kind+'Result');img.src=out.toDataURL('image/png');img.classList.remove('hidden');$(kind+'ResultText').textContent=kind==='trainer'?'Square crop ready for the card.':'Circular crop ready for the card.';drawAll();}
function editorPoint(e,c){const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height};}
function pointerDown(kind,e){const c=$(kind+'CropCanvas'),q=editorPoint(e,c),min=Math.min(c.width,c.height),handle=Math.max(28,c.width/32);if(kind==='trainer'){const s=S.trainerCrop,side=s.size*min,x=s.cx*c.width-side/2,y=s.cy*c.height-side/2,hx=x+side,hy=y+side;if(Math.hypot(q.x-hx,q.y-hy)<handle)S.drag={kind,mode:'resize',sx:q.x,sy:q.y,start:{...s}};else if(q.x>=x&&q.x<=x+side&&q.y>=y&&q.y<=y+side)S.drag={kind,mode:'move',sx:q.x,sy:q.y,start:{...s}};}else{const s=S.buddyCrop,r=s.r*min,cx=s.cx*c.width,cy=s.cy*c.height;if(Math.hypot(q.x-(cx+r),q.y-cy)<handle)S.drag={kind,mode:'resize',sx:q.x,sy:q.y,start:{...s}};else if(Math.hypot(q.x-cx,q.y-cy)<=r)S.drag={kind,mode:'move',sx:q.x,sy:q.y,start:{...s}};}if(S.drag){c.setPointerCapture?.(e.pointerId);e.preventDefault();}}
function pointerMove(kind,e){if(!S.drag||S.drag.kind!==kind)return;const c=$(kind+'CropCanvas'),q=editorPoint(e,c),dx=(q.x-S.drag.sx)/c.width,dy=(q.y-S.drag.sy)/c.height,min=Math.min(c.width,c.height);if(kind==='trainer'){const s=S.drag.start;if(S.drag.mode==='move'){const half=s.size*min/2;S.trainerCrop.cx=clamp(s.cx+dx,half/c.width,1-half/c.width);S.trainerCrop.cy=clamp(s.cy+dy,half/c.height,1-half/c.height);}else{const delta=((q.x-S.drag.sx)+(q.y-S.drag.sy))/2/min;const size=clamp(s.size+delta,.18,.94);S.trainerCrop.size=size;const half=size*min/2;S.trainerCrop.cx=clamp(S.trainerCrop.cx,half/c.width,1-half/c.width);S.trainerCrop.cy=clamp(S.trainerCrop.cy,half/c.height,1-half/c.height);}}else{const s=S.drag.start;if(S.drag.mode==='move'){const rr=s.r*min;S.buddyCrop.cx=clamp(s.cx+dx,rr/c.width,1-rr/c.width);S.buddyCrop.cy=clamp(s.cy+dy,rr/c.height,1-rr/c.height);}else{const delta=(q.x-S.drag.sx)/min,Sr=clamp(s.r+delta,.08,.46);S.buddyCrop.r=Sr;const rr=Sr*min;S.buddyCrop.cx=clamp(S.buddyCrop.cx,rr/c.width,1-rr/c.width);S.buddyCrop.cy=clamp(S.buddyCrop.cy,rr/c.height,1-rr/c.height);}}drawCropEditor(kind);e.preventDefault();}
function pointerUp(kind,e){if(!S.drag||S.drag.kind!==kind)return;S.drag=null;applyCrop(kind);e.preventDefault();}
function roundRect(g,x,y,w,h,r){g.beginPath();g.roundRect(x,y,w,h,r);}
function hsl(h,s,l,a=1){return `hsla(${((h%360)+360)%360},${s}%,${l}%,${a})`;}
function drawBg(g){const h=TEAM[S.team].hue,grad=g.createLinearGradient(0,0,900,1400);grad.addColorStop(0,hsl(h,76,56));grad.addColorStop(.48,hsl(h+18,58,28));grad.addColorStop(1,hsl(h-15,45,10));g.fillStyle=grad;g.fillRect(0,0,900,1400);g.save();g.globalAlpha=.10;g.strokeStyle='#fff';g.lineWidth=3;for(let r=120;r<760;r+=110){g.beginPath();g.arc(790,205,r,0,Math.PI*2);g.stroke();}g.globalAlpha=.06;g.lineWidth=35;for(let x=-450;x<1200;x+=190){g.beginPath();g.moveTo(x,1360);g.lineTo(x+640,0);g.stroke();}g.restore();g.strokeStyle='rgba(255,255,255,.35)';g.lineWidth=4;roundRect(g,22,22,856,1356,48);g.stroke();g.strokeStyle='rgba(255,255,255,.12)';g.lineWidth=2;roundRect(g,37,37,826,1326,40);g.stroke();}
function fitText(g,text,x,y,max,size,weight=900,align='left'){let s=size;g.textAlign=align;g.textBaseline='middle';while(s>12){g.font=`${weight} ${s}px system-ui`;if(g.measureText(text||'—').width<=max)break;s--;}g.fillText(text||'—',x,y,max);}
function drawSquare(g,img,x,y,size){roundRect(g,x,y,size,size,32);g.save();g.clip();if(img)g.drawImage(img,x,y,size,size);else{g.fillStyle='rgba(4,8,12,.50)';g.fillRect(x,y,size,size);g.fillStyle='rgba(255,255,255,.65)';g.textAlign='center';g.font='800 22px system-ui';g.fillText('ADD TRAINER',x+size/2,y+size/2);}g.restore();g.strokeStyle='rgba(255,255,255,.28)';g.lineWidth=3;roundRect(g,x,y,size,size,32);g.stroke();}
function drawCircle(g,img,cx,cy,r){g.save();g.beginPath();g.arc(cx,cy,r,0,Math.PI*2);g.clip();if(img)g.drawImage(img,cx-r,cy-r,r*2,r*2);else{g.fillStyle='rgba(4,8,12,.62)';g.fillRect(cx-r,cy-r,r*2,r*2);g.fillStyle='rgba(255,255,255,.65)';g.textAlign='center';g.font='800 20px system-ui';g.fillText('BUDDY',cx,cy);}g.restore();g.strokeStyle='rgba(255,255,255,.52)';g.lineWidth=5;g.beginPath();g.arc(cx,cy,r,0,Math.PI*2);g.stroke();}
function drawFront(){const c=$('cardCanvas'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);drawBg(g);g.fillStyle='rgba(0,0,0,.18)';roundRect(g,72,120,756,865,42);g.fill();g.fillStyle='rgba(255,255,255,.75)';g.font='800 20px system-ui';g.textAlign='left';g.fillText('TRAINER CARD',90,85);g.fillStyle='#fff';fitText(g,$('trainerName').value.trim()||'TRAINER',90,165,610,54,950);g.fillStyle='rgba(255,255,255,.75)';g.font='800 18px system-ui';g.textAlign='right';g.fillText(`LV. ${$('level').value.trim()||'—'}`,805,165);drawSquare(g,S.trainerCanvas,105,215,520);drawCircle(g,S.buddyCanvas,686,390,122);g.fillStyle='rgba(255,255,255,.70)';g.font='800 14px system-ui';g.textAlign='center';g.fillText('BUDDY',686,538);g.fillStyle='#fff';fitText(g,$('buddy').value.trim()||'—',686,566,235,24,900,'center');const stats=[['POKÉMON CAUGHT',$('caught').value,180],['POKÉSTOPS VISITED',$('stops').value,450],['TOTAL XP',$('xp').value,720]];for(const[label,val,x]of stats){g.fillStyle='rgba(255,255,255,.68)';g.font='800 13px system-ui';g.textAlign='center';g.fillText(label,x,1070);g.fillStyle='#fff';fitText(g,val.trim()||'—',x,1110,230,28,950,'center');}g.fillStyle='rgba(255,255,255,.64)';g.font='700 14px system-ui';g.textAlign='left';g.fillText(`START  ${$('startDate').value.trim()||'—'}`,95,1260);g.textAlign='right';g.fillText(`PRINT  ${$('printDate').value.trim()||'—'}`,805,1260);g.fillStyle='rgba(255,255,255,.38)';g.font='700 11px system-ui';g.textAlign='center';g.fillText(`${TEAM[S.team].name.toUpperCase()} · CUSTOM TRAINER CARD`,450,1325);}
function drawBack(){const c=$('backCanvas'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);drawBg(g);g.fillStyle='#fff';fitText(g,$('trainerName').value.trim()||'TRAINER',450,145,650,48,950,'center');g.fillStyle='rgba(255,255,255,.72)';g.font='800 16px system-ui';g.textAlign='center';g.fillText(TEAM[S.team].name.toUpperCase(),450,196);g.fillStyle='rgba(0,0,0,.30)';roundRect(g,145,275,610,690,42);g.fill();g.fillStyle='#fff';roundRect(g,245,355,410,410,28);g.fill();if(S.qrCrop)g.drawImage(S.qrCrop,270,380,360,360);else{g.fillStyle='#161b24';g.font='800 20px system-ui';g.textAlign='center';g.fillText('UPLOAD TRAINER CODE',450,555);}g.fillStyle='#fff';fitText(g,formatCode($('trainerCode').value)||'••••  ••••  ••••',450,840,520,34,950,'center');g.fillStyle='rgba(255,255,255,.65)';g.font='800 13px system-ui';g.fillText('TRAINER CODE',450,885);g.fillStyle='rgba(255,255,255,.60)';g.font='700 13px system-ui';g.fillText(`LEVEL ${$('level').value.trim()||'—'}   ·   BUDDY ${$('buddy').value.trim()||'—'}`,450,1050);g.fillText(`PRINT ${$('printDate').value.trim()||'—'}`,450,1250);}
function drawAll(){drawFront();drawBack();}
function formatCode(v){const d=(v||'').replace(/\D/g,'').slice(0,12);return d.replace(/(\d{4})(?=\d)/g,'$1  ').trim();}
function canvasFromImage(img){const max=1800,s=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),c=document.createElement('canvas');c.width=Math.round(img.naturalWidth*s);c.height=Math.round(img.naturalHeight*s);c.getContext('2d',{willReadFrequently:true}).drawImage(img,0,0,c.width,c.height);return c;}
function qrCropFrom(c,b){if(!b)return null;const p=Math.max(b.width,b.height)*.12,x=Math.max(0,b.x-p),y=Math.max(0,b.y-p),w=Math.min(c.width-x,b.width+2*p),h=Math.min(c.height-y,b.height+2*p),side=Math.min(c.width,c.height,Math.max(w,h)),cx=x+w/2,cy=y+h/2,sx=Math.max(0,Math.min(c.width-side,cx-side/2)),sy=Math.max(0,Math.min(c.height-side,cy-side/2)),o=document.createElement('canvas');o.width=o.height=640;o.getContext('2d').drawImage(c,sx,sy,side,side,0,0,640,640);return o;}
const extractCode=t=>{let m=t.match(/\b\d{4}[\s-]+\d{4}[\s-]+\d{4}\b/);if(m)return m[0].replace(/\D/g,'');m=t.match(/(?:^|\D)(\d{12})(?:\D|$)/);if(m)return m[1];for(const line of t.split(/[\r\n]+/)){const d=line.replace(/\D/g,'');if(d.length===12)return d;}return'';};
async function scanCode(){if(!S.codeImage)return;$('codeStatus').textContent='Scanning…';try{const c=canvasFromImage(S.codeImage);let raw='';S.qrCrop=null;if('BarcodeDetector'in window)try{const d=new BarcodeDetector({formats:['qr_code']}),r=await d.detect(c);if(r.length){raw=r[0].rawValue||'';S.qrCrop=qrCropFrom(c,r[0].boundingBox);}}catch{}if(!S.qrCrop&&window.jsQR){const g=c.getContext('2d',{willReadFrequently:true}),im=g.getImageData(0,0,c.width,c.height),r=window.jsQR(im.data,c.width,c.height,{inversionAttempts:'attemptBoth'});if(r){raw=r.data||'';const p=[r.location.topLeftCorner,r.location.topRightCorner,r.location.bottomLeftCorner,r.location.bottomRightCorner],x=Math.min(...p.map(q=>q.x)),X=Math.max(...p.map(q=>q.x)),y=Math.min(...p.map(q=>q.y)),Y=Math.max(...p.map(q=>q.y));S.qrCrop=qrCropFrom(c,{x,y,width:X-x,height:Y-y});}}let code=extractCode(raw);if(!code){for(const psm of ['6','11']){const r=await read(c,psm,'0123456789 -');code=extractCode(r.text);if(code)break;}}if(code){$('trainerCode').value=formatCode(code);$('codeState').textContent='Detected';$('codeState').className='ok';}else{$('codeState').textContent='Review';$('codeState').className='review';}$('qrStatus').textContent=S.qrCrop?'QR detected':'QR needs review';$('codeStatus').textContent=code&&S.qrCrop?'Ready':'Review';drawBack();}catch(e){console.error(e);$('codeStatus').textContent='Review';}}
async function handleInfo(file){if(!file)return;const r=await loadFile(file);revoke(S.infoURL);S.infoURL=r.url;S.infoImage=r.img;$('infoThumb').src=r.url;$('infoName').textContent=file.name;$('infoMeta').textContent=meta(file);$('infoSourceCard').classList.remove('hidden');$('ocrAgainBtn').disabled=false;$('cardEmpty').classList.add('hidden');$('saveBtn').disabled=false;await scanInfo();}
async function handleVisual(kind,file){if(!file)return;const r=await loadFile(file);revoke(S[kind+'URL']);S[kind+'URL']=r.url;S[kind+'Source']=r.img;$(kind+'SourceThumb').src=r.url;$(kind+'SourceName').textContent=file.name;$(kind+'SourceMeta').textContent=meta(file);$(kind+'SourceCard').classList.remove('hidden');$(kind+'CropEmpty').classList.add('hidden');if(kind==='trainer')S.trainerCrop={cx:.5,cy:.42,size:.62};else S.buddyCrop={cx:.5,cy:.42,r:.31};setupCropCanvas(kind);applyCrop(kind);}
function reset(){['trainerName','level','buddy','caught','stops','xp','startDate','trainerCode'].forEach(id=>{$(id).value='';if(id!=='trainerCode')setState(id,'manual');});$('printDate').value=today();revoke(S.infoURL);revoke(S.trainerURL);revoke(S.buddyURL);revoke(S.codeURL);Object.assign(S,{infoImage:null,infoURL:'',trainerSource:null,trainerURL:'',buddySource:null,buddyURL:'',trainerCanvas:null,buddyCanvas:null,codeImage:null,codeURL:'',qrCrop:null,showBack:false,drag:null});['infoSourceCard','trainerSourceCard','buddySourceCard','codeSourceCard'].forEach(id=>$(id)?.classList.add('hidden'));['trainerCropEmpty','buddyCropEmpty'].forEach(id=>$(id)?.classList.remove('hidden'));['trainerResult','buddyResult'].forEach(id=>$(id)?.classList.add('hidden'));$('cardEmpty').classList.remove('hidden');$('saveBtn').disabled=true;$('ocrAgainBtn').disabled=true;$('rescanCodeBtn').disabled=true;$('cardFlipper').classList.remove('flipped');$('sidePill').textContent='Front';$('teamStatus').textContent='Waiting for screenshot';$('qualityText').textContent='0%';setTeam('valor',false);$('teamStatus').textContent='Waiting for screenshot';drawAll();}
document.addEventListener('DOMContentLoaded',()=>{setTheme();$('printDate').value=today();drawAll();$('profileInput').addEventListener('change',e=>handleInfo(e.target.files?.[0]));$('trainerShotInput').addEventListener('change',e=>handleVisual('trainer',e.target.files?.[0]));$('buddyShotInput').addEventListener('change',e=>handleVisual('buddy',e.target.files?.[0]));$('codeInput').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;const r=await loadFile(f);revoke(S.codeURL);S.codeURL=r.url;S.codeImage=r.img;$('codeThumb').src=r.url;$('codeName').textContent=f.name;$('codeMeta').textContent=meta(f);$('codeSourceCard').classList.remove('hidden');$('rescanCodeBtn').disabled=false;await scanCode();});$('ocrAgainBtn').addEventListener('click',scanInfo);$('rescanCodeBtn').addEventListener('click',scanCode);document.querySelectorAll('.team').forEach(b=>b.addEventListener('click',()=>setTeam(b.dataset.team,false)));['trainerName','level','buddy','caught','stops','xp','startDate','printDate','trainerCode'].forEach(id=>$(id).addEventListener('input',()=>{if(['trainerName','level','buddy','caught','stops','xp','startDate'].includes(id))setState(id,'manual');updateQuality();drawAll();}));$('trainerCode').addEventListener('blur',()=>{$('trainerCode').value=formatCode($('trainerCode').value);drawBack();});['trainer','buddy'].forEach(kind=>{const c=$(kind+'CropCanvas');c.addEventListener('pointerdown',e=>pointerDown(kind,e));c.addEventListener('pointermove',e=>pointerMove(kind,e));c.addEventListener('pointerup',e=>pointerUp(kind,e));c.addEventListener('pointercancel',e=>pointerUp(kind,e));$(kind+'ApplyCrop').addEventListener('click',()=>applyCrop(kind));});const flip=()=>{S.showBack=!S.showBack;$('cardFlipper').classList.toggle('flipped',S.showBack);$('sidePill').textContent=S.showBack?'Back':'Front';$('saveBtn').querySelector('small').textContent=(S.showBack?'Back':'Front')+' · PNG';};$('flipBtn').addEventListener('click',e=>{e.stopPropagation();flip();});$('cardStage').addEventListener('click',flip);$('cardStage').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();flip();}});$('saveBtn').addEventListener('click',()=>{drawAll();const c=S.showBack?$('backCanvas'):$('cardCanvas'),a=document.createElement('a');a.href=c.toDataURL('image/png');a.download=`${($('trainerName').value||'trainer').replace(/\W+/g,'_')}_${S.team}_${S.showBack?'back':'front'}_v26.png`;a.click();});$('resetBtn').addEventListener('click',reset);window.addEventListener('resize',()=>{if(S.trainerSource)setupCropCanvas('trainer');if(S.buddySource)setupCropCanvas('buddy');});});
})();