(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  const TEAM={valor:{name:'Valor',hue:354},mystic:{name:'Mystic',hue:205},instinct:{name:'Instinct',hue:48}};
  const S={team:'valor',sourceImage:null,sourceURL:'',trainerImage:null,trainerURL:'',buddyImage:null,buddyURL:'',codeImage:null,codeURL:'',qrCrop:null,ocr:null,scanning:false,codeScanning:false,showBack:false,trainerPose:{zoom:1,x:0,y:0},buddyPose:{zoom:1,x:0,y:0},hue:354,sat:76,light:48};

  const toast=msg=>{const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),2600);};
  const today=()=>new Date().toLocaleDateString('en-US',{month:'numeric',day:'numeric',year:'numeric'});
  const revoke=u=>{if(u)URL.revokeObjectURL(u);};
  const loadFile=file=>new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>resolve({img,url});img.onerror=e=>{URL.revokeObjectURL(url);reject(e);};img.src=url;});
  const fileMeta=f=>`${Math.round(f.size/1024)} KB · ${f.type||'image'}`;
  const norm=s=>(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');
  const fmtNum=d=>d.replace(/\B(?=(\d{3})+(?!\d))/g,',');
  const cleanDate=t=>(t.match(/\b\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4}\b/)||[])[0]||'';

  function setFieldState(id,state){const e=$(id+'State');if(!e)return;e.textContent=state==='ok'?'Detected':state==='review'?'Review':'Manual';e.className=state==='ok'?'ok':state==='review'?'review':'';}
  function updateQuality(){const ids=['trainerName','level','buddy','caught','stops','xp','startDate'];const n=ids.filter(id=>$(id).value.trim()).length;$('qualityText').textContent=`${Math.round(n/ids.length*100)}%`;}
  function hsl(h,s,l,a=1){return `hsla(${((h%360)+360)%360},${s}%,${l}%,${a})`;}
  function syncTheme(){document.documentElement.style.setProperty('--accent',hsl(S.hue,Math.min(95,S.sat),58));document.documentElement.style.setProperty('--accent2',hsl(S.hue+18,Math.max(45,S.sat-8),72));$('hueOut').textContent=`${S.hue}°`;$('satOut').textContent=`${S.sat}%`;$('lightOut').textContent=`${S.light}%`;$('colorSwatch').style.background=`linear-gradient(135deg,${hsl(S.hue,S.sat,Math.min(72,S.light+10))},${hsl(S.hue+28,S.sat,Math.max(18,S.light-18))})`;drawAll();}
  function setTeam(team,detected=false,resetColor=true){if(!TEAM[team])return;S.team=team;if(resetColor){S.hue=TEAM[team].hue;$('hue').value=S.hue;}document.querySelectorAll('.team').forEach(b=>b.classList.toggle('active',b.dataset.team===team));$('teamStatus').textContent=`${detected?'Detected':'Selected'}: ${TEAM[team].name}`;$('previewTeam').textContent=TEAM[team].name;syncTheme();}

  function detectTeam(img){const c=document.createElement('canvas');c.width=240;c.height=360;const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(img,0,0,c.width,c.height);const d=g.getImageData(0,0,c.width,c.height).data;let R=0,B=0,Y=0;for(let i=0;i<d.length;i+=20){const r=d[i],gg=d[i+1],b=d[i+2],mx=Math.max(r,gg,b),mn=Math.min(r,gg,b);if(mx-mn<25)continue;R+=Math.max(0,r-(gg+b)/2);B+=Math.max(0,b-(r+gg)/2);Y+=Math.max(0,Math.min(r,gg)-b*.72);}return Object.entries({valor:R,mystic:B,instinct:Y}).sort((a,b)=>b[1]-a[1])[0][0];}

  async function worker(){if(!S.ocr)S.ocr=await Tesseract.createWorker('eng',1,{logger:m=>{if(m.status==='recognizing text'&&$('scanPct'))$('scanPct').textContent=`${Math.round((m.progress||0)*100)}%`;}});return S.ocr;}
  async function read(canvas,psm='7',whitelist=''){const w=await worker();await w.setParameters({tessedit_pageseg_mode:psm,...(whitelist?{tessedit_char_whitelist:whitelist}:{})});const r=await w.recognize(canvas);return{text:r.data.text||'',confidence:r.data.confidence||0};}
  function crop(img,x,y,w,h,scale=6,mode='normal'){const iw=img.naturalWidth||img.width,ih=img.naturalHeight||img.height,c=document.createElement('canvas');c.width=Math.max(1,Math.round(iw*w*scale));c.height=Math.max(1,Math.round(ih*h*scale));const g=c.getContext('2d',{willReadFrequently:true});g.imageSmoothingEnabled=true;g.imageSmoothingQuality='high';g.drawImage(img,iw*x,ih*y,iw*w,ih*h,0,0,c.width,c.height);if(mode!=='normal'){const im=g.getImageData(0,0,c.width,c.height),d=im.data;for(let i=0;i<d.length;i+=4){const r=d[i],gg=d[i+1],b=d[i+2];let hit=false;if(mode==='maroon')hit=r>75&&r>gg*1.18&&r>b*1.08&&gg<185;if(mode==='green')hit=gg>85&&gg>r*1.04&&gg>b*.88;if(mode==='red')hit=r>95&&r>gg*1.12&&r>b*1.04;if(mode==='dark')hit=(r+gg+b)<430;const v=hit?0:255;d[i]=d[i+1]=d[i+2]=v;d[i+3]=255;}g.putImageData(im,0,0);}return c;}
  function textTokens(text,allowDigits=true){const out=[];for(const line of (text||'').split(/[\r\n]+/)){const compact=line.replace(allowDigits?/[^A-Za-z0-9_-]/g:/[^A-Za-z-]/g,'').replace(/^[_-]+|[_-]+$/g,'');if(compact.length>=2&&compact.length<=28)out.push(compact);const re=allowDigits?/[A-Za-z][A-Za-z0-9_-]{1,27}/g:/[A-Za-z][A-Za-z-]{1,27}/g;out.push(...(line.match(re)||[]));}return[...new Set(out.filter(Boolean))];}
  function literalConsensus(reads,{allowDigits=true,blocked=[]}={}){const stop=new Set(blocked.map(norm)),groups=new Map();for(const r of reads){for(const t of textTokens(r.text,allowDigits)){const k=norm(t);if(!k||stop.has(k)||/^\d+$/.test(t))continue;const g=groups.get(k)||{value:t,count:0,total:0,max:0};g.count++;g.total+=Number(r.confidence||0);g.max=Math.max(g.max,Number(r.confidence||0));if(t.length>g.value.length)g.value=t;groups.set(k,g);}}let best=null;for(const g of groups.values()){g.avg=g.total/g.count;g.score=g.count*70+g.avg+Math.min(g.value.length,18);if(!best||g.score>best.score)best=g;}return best||{value:'',count:0,max:0};}
  function numberFrom(text){const ms=(text||'').match(/[\d][\d,\.\s]*/g)||[],ds=ms.map(s=>s.replace(/\D/g,'')).filter(Boolean);return ds.sort((a,b)=>b.length-a.length)[0]||'';}
  function consensusNumber(reads,{minDigits=1,maxDigits=12,maxValue=Number.MAX_SAFE_INTEGER}={}){const map=new Map();for(const r of reads){const d=numberFrom(r.text);if(!d||d.length<minDigits||d.length>maxDigits||Number(d)>maxValue)continue;const v=map.get(d)||{digits:d,count:0,confidence:0};v.count++;v.confidence=Math.max(v.confidence,r.confidence||0);map.set(d,v);}return[...map.values()].sort((a,b)=>b.count-a.count||b.confidence-a.confidence)[0]||null;}
  function consensusDate(reads){const map=new Map();for(const r of reads){const d=cleanDate(r.text);if(!d)continue;const v=map.get(d)||{value:d,count:0,confidence:0};v.count++;v.confidence=Math.max(v.confidence,r.confidence||0);map.set(d,v);}return[...map.values()].sort((a,b)=>b.count-a.count||b.confidence-a.confidence)[0]||null;}
  async function readSet(normal,masked,whitelist){return[await read(normal,'7',whitelist),await read(masked,'7',whitelist),await read(normal,'6',whitelist),await read(masked,'13',whitelist)];}

  async function scanProfile(){if(!S.sourceImage||S.scanning)return;S.scanning=true;$('scanCard').classList.remove('hidden');$('scanTitle').textContent='Reading screenshot with OCR';$('scanPct').textContent='0%';['trainerName','level','buddy','caught','stops','xp','startDate'].forEach(id=>{setFieldState(id,'manual');});try{
      setTeam(detectTeam(S.sourceImage),true,true);
      $('scanDetail').textContent='Trainer name';let normal=crop(S.sourceImage,.045,.126,.40,.038,7),mask=crop(S.sourceImage,.045,.126,.40,.038,7,'maroon');let reads=await readSet(normal,mask,'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-');let pick=literalConsensus(reads,{allowDigits:true,blocked:['me','friends','social','level','buddy','history','scrapbook','journal','style','total','activity']});if(pick.value){$('trainerName').value=pick.value;setFieldState('trainerName',pick.count>=2||pick.max>=72?'ok':'review');}else setFieldState('trainerName','review');
      $('scanDetail').textContent='Buddy name';normal=crop(S.sourceImage,.045,.151,.40,.036,8);mask=crop(S.sourceImage,.045,.151,.40,.036,8,'maroon');reads=await readSet(normal,mask,'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-');pick=literalConsensus(reads,{allowDigits:false,blocked:['buddy','history','scrapbook','journal','style','friends','social','me','mega','cp',$('trainerName').value]});if(pick.value){$('buddy').value=pick.value;setFieldState('buddy',pick.count>=2||pick.max>=72?'ok':'review');}else setFieldState('buddy','review');
      const jobs=[['level','Level',[.055,.526,.16,.050],'red','0123456789',{minDigits:1,maxDigits:3,maxValue:100}],['caught','Pokémon caught',[.585,.792,.30,.035],'green','0123456789,',{minDigits:2,maxDigits:9}],['stops','PokéStops visited',[.585,.831,.30,.035],'green','0123456789,',{minDigits:2,maxDigits:9}],['xp','Total XP',[.585,.870,.36,.035],'green','0123456789,',{minDigits:4,maxDigits:12}],['startDate','Start date',[.585,.909,.30,.035],'green','0123456789/-',null]];
      for(const [id,label,r,mode,whitelist,rules] of jobs){$('scanDetail').textContent=label;normal=crop(S.sourceImage,...r,6);mask=crop(S.sourceImage,...r,6,mode);reads=await readSet(normal,mask,whitelist);if(id==='startDate'){const p=consensusDate(reads);if(p){$(id).value=p.value;setFieldState(id,p.count>=2?'ok':'review');}else setFieldState(id,'review');}else{const p=consensusNumber(reads,rules||{});if(p){$(id).value=id==='level'?String(Number(p.digits)):fmtNum(p.digits);setFieldState(id,p.count>=2?'ok':'review');}else setFieldState(id,'review');}}
      updateQuality();toast('OCR filled what it could. Review any field marked Review.');
    }catch(e){console.error(e);toast('OCR could not finish. You can enter the fields manually.');}finally{S.scanning=false;$('scanCard').classList.add('hidden');drawAll();}}

  function roundRectPath(g,x,y,w,h,r){g.beginPath();g.roundRect(x,y,w,h,r);}
  function drawBackground(g){const h=S.hue,s=S.sat,l=S.light;const grad=g.createLinearGradient(0,0,900,1400);grad.addColorStop(0,hsl(h,s,Math.min(65,l+8)));grad.addColorStop(.48,hsl(h+18,Math.max(38,s-18),Math.max(18,l-18)));grad.addColorStop(1,hsl(h-18,Math.max(30,s-25),10));g.fillStyle=grad;g.fillRect(0,0,900,1400);
    const shade=g.createLinearGradient(0,0,0,1400);shade.addColorStop(0,'rgba(0,0,0,.04)');shade.addColorStop(.55,'rgba(0,0,0,.18)');shade.addColorStop(1,'rgba(0,0,0,.55)');g.fillStyle=shade;g.fillRect(0,0,900,1400);
    g.save();g.globalAlpha=.11;g.strokeStyle='#fff';g.lineWidth=3;for(let r=130;r<760;r+=105){g.beginPath();g.arc(780,210,r,0,Math.PI*2);g.stroke();}g.globalAlpha=.07;g.lineWidth=34;for(let x=-420;x<1200;x+=180){g.beginPath();g.moveTo(x,1320);g.lineTo(x+620,0);g.stroke();}g.restore();
    g.strokeStyle='rgba(255,255,255,.32)';g.lineWidth=3;roundRectPath(g,20,20,860,1360,52);g.stroke();g.strokeStyle='rgba(255,255,255,.10)';g.lineWidth=1;roundRectPath(g,35,35,830,1330,43);g.stroke();
  }
  function fitText(g,text,x,y,max,size,weight=900,align='left'){let s=size;g.textAlign=align;g.textBaseline='middle';while(s>12){g.font=`${weight} ${s}px system-ui,-apple-system,"Segoe UI",sans-serif`;if(g.measureText(text||'—').width<=max)break;s-=1;}g.fillText(text||'—',x,y,max);}
  function drawCover(g,img,x,y,w,h,pose,r=28){roundRectPath(g,x,y,w,h,r);g.save();g.clip();if(!img){g.fillStyle='rgba(7,10,15,.42)';g.fillRect(x,y,w,h);g.fillStyle='rgba(255,255,255,.65)';g.textAlign='center';g.textBaseline='middle';g.font='800 22px system-ui';g.fillText('ADD TRAINER IMAGE',x+w/2,y+h/2);g.restore();return;}const iw=img.naturalWidth||img.width,ih=img.naturalHeight||img.height,scale=Math.max(w/iw,h/ih)*(pose.zoom||1),nw=iw*scale,nh=ih*scale,dx=x+(w-nw)/2+(pose.x||0)*w*.22,dy=y+(h-nh)/2+(pose.y||0)*h*.22;g.drawImage(img,dx,dy,nw,nh);g.restore();}
  function drawCircleImage(g,img,cx,cy,r,pose){g.save();g.beginPath();g.arc(cx,cy,r,0,Math.PI*2);g.clip();if(!img){g.fillStyle='rgba(8,11,16,.72)';g.fillRect(cx-r,cy-r,r*2,r*2);g.fillStyle='rgba(255,255,255,.62)';g.textAlign='center';g.textBaseline='middle';g.font='800 18px system-ui';g.fillText('BUDDY',cx,cy);}else{const iw=img.naturalWidth||img.width,ih=img.naturalHeight||img.height,d=r*2,scale=Math.max(d/iw,d/ih)*(pose.zoom||1),nw=iw*scale,nh=ih*scale;g.drawImage(img,cx-nw/2+(pose.x||0)*d*.20,cy-nh/2+(pose.y||0)*d*.20,nw,nh);}g.restore();g.strokeStyle='rgba(255,255,255,.85)';g.lineWidth=8;g.beginPath();g.arc(cx,cy,r+3,0,Math.PI*2);g.stroke();g.strokeStyle=hsl(S.hue,S.sat,65,.9);g.lineWidth=4;g.beginPath();g.arc(cx,cy,r+12,0,Math.PI*2);g.stroke();}
  function stat(g,label,value,x,y,w){g.fillStyle='rgba(5,8,13,.44)';roundRectPath(g,x,y,w,126,22);g.fill();g.strokeStyle='rgba(255,255,255,.14)';g.lineWidth=2;g.stroke();g.fillStyle='rgba(255,255,255,.66)';g.font='800 18px system-ui';g.textAlign='left';g.textBaseline='middle';g.fillText(label,x+24,y+34);g.fillStyle='#fff';fitText(g,value||'—',x+24,y+82,w-48,34,900,'left');}
  function teamMark(g){const x=740,y=92;g.fillStyle='rgba(6,9,14,.42)';g.beginPath();for(let i=0;i<6;i++){const a=Math.PI/3*i-Math.PI/6,px=x+62*Math.cos(a),py=y+62*Math.sin(a);i?g.lineTo(px,py):g.moveTo(px,py);}g.closePath();g.fill();g.strokeStyle='rgba(255,255,255,.45)';g.lineWidth=3;g.stroke();g.fillStyle='#fff';g.textAlign='center';g.textBaseline='middle';g.font='950 44px system-ui';g.fillText(S.team==='valor'?'V':S.team==='mystic'?'M':'I',x,y+1);}

  function drawFront(){const c=$('cardCanvas'),g=c.getContext('2d');c.width=900;c.height=1400;g.clearRect(0,0,900,1400);drawBackground(g);teamMark(g);g.fillStyle='rgba(255,255,255,.72)';g.font='800 19px system-ui';g.textAlign='left';g.fillText('TRAINER PROFILE',64,74);g.fillStyle='#fff';fitText(g,$('trainerName').value.trim()||'YOUR TRAINER NAME',64,132,610,52,950,'left');g.fillStyle='rgba(255,255,255,.70)';g.font='800 21px system-ui';g.fillText(`LEVEL ${$('level').value.trim()||'—'}  ·  ${TEAM[S.team].name.toUpperCase()}`,66,176);
    g.fillStyle='rgba(4,7,12,.26)';roundRectPath(g,55,215,790,575,34);g.fill();g.strokeStyle='rgba(255,255,255,.17)';g.lineWidth=2;g.stroke();drawCover(g,S.trainerImage,72,232,756,530,S.trainerPose,27);drawCircleImage(g,S.buddyImage,713,725,96,S.buddyPose);
    g.fillStyle='rgba(5,8,13,.52)';roundRectPath(g,55,820,790,92,22);g.fill();g.fillStyle='rgba(255,255,255,.60)';g.font='800 17px system-ui';g.fillText('BUDDY',80,848);g.fillStyle='#fff';fitText(g,$('buddy').value.trim()||'—',80,882,720,30,900,'left');
    stat(g,'POKÉMON CAUGHT',$('caught').value.trim(),55,942,250);stat(g,'POKÉSTOPS VISITED',$('stops').value.trim(),325,942,250);stat(g,'TOTAL XP',$('xp').value.trim(),595,942,250);
    g.fillStyle='rgba(5,8,13,.40)';roundRectPath(g,55,1090,790,118,22);g.fill();g.fillStyle='rgba(255,255,255,.62)';g.font='800 17px system-ui';g.fillText('START DATE',80,1127);g.fillText('PRINT DATE',490,1127);g.fillStyle='#fff';fitText(g,$('startDate').value.trim()||'—',80,1170,320,30,900,'left');fitText(g,$('printDate').value.trim()||'—',490,1170,300,30,900,'left');
    g.fillStyle='rgba(255,255,255,.48)';g.font='750 15px system-ui';g.textAlign='center';g.fillText('CUSTOM TRAINER CARD · UNOFFICIAL FAN-MADE PROFILE',450,1322);
  }

  function drawBack(){const c=$('backCanvas'),g=c.getContext('2d');c.width=900;c.height=1400;g.clearRect(0,0,900,1400);drawBackground(g);teamMark(g);g.fillStyle='rgba(255,255,255,.72)';g.font='800 19px system-ui';g.textAlign='left';g.fillText('TRAINER CONNECTION',64,74);g.fillStyle='#fff';fitText(g,$('trainerName').value.trim()||'YOUR TRAINER NAME',64,132,610,48,950,'left');g.fillStyle='rgba(255,255,255,.65)';g.font='800 20px system-ui';g.fillText(`${TEAM[S.team].name.toUpperCase()} · LEVEL ${$('level').value.trim()||'—'}`,66,176);
    g.fillStyle='rgba(255,255,255,.96)';roundRectPath(g,145,245,610,610,36);g.fill();if(S.qrCrop){const iw=S.qrCrop.width,ih=S.qrCrop.height,side=Math.min(iw,ih);g.drawImage(S.qrCrop,(iw-side)/2,(ih-side)/2,side,side,180,280,540,540);}else{g.fillStyle='#151a22';g.textAlign='center';g.textBaseline='middle';g.font='900 28px system-ui';g.fillText('UPLOAD TRAINER CODE SCREEN',450,530);g.fillStyle='#697586';g.font='700 19px system-ui';g.fillText('QR code will appear here',450,575);}
    g.fillStyle='rgba(5,8,13,.50)';roundRectPath(g,110,900,680,148,26);g.fill();g.fillStyle='rgba(255,255,255,.60)';g.font='800 18px system-ui';g.textAlign='center';g.fillText('TRAINER CODE',450,936);g.fillStyle='#fff';fitText(g,formatCode($('trainerCode').value)||'••••  ••••  ••••',450,992,610,43,950,'center');
    stat(g,'BUDDY',$('buddy').value.trim(),110,1082,330);stat(g,'TEAM',TEAM[S.team].name,460,1082,330);g.fillStyle='rgba(255,255,255,.48)';g.font='750 15px system-ui';g.textAlign='center';g.fillText('CUSTOM TRAINER CARD · UNOFFICIAL FAN-MADE PROFILE',450,1322);
  }
  function drawAll(){if(!$('cardCanvas'))return;drawFront();drawBack();}
  function formatCode(v){const d=(v||'').replace(/\D/g,'').slice(0,12);return d.replace(/(\d{4})(?=\d)/g,'$1  ').trim();}

  function canvasFrom(img){const max=1800,s=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),c=document.createElement('canvas');c.width=Math.round(img.naturalWidth*s);c.height=Math.round(img.naturalHeight*s);c.getContext('2d',{willReadFrequently:true}).drawImage(img,0,0,c.width,c.height);return c;}
  function qrCrop(c,b){if(!b)return null;const p=Math.max(b.width,b.height)*.12,x=Math.max(0,b.x-p),y=Math.max(0,b.y-p),w=Math.min(c.width-x,b.width+2*p),h=Math.min(c.height-y,b.height+2*p),side=Math.min(c.width,c.height,Math.max(w,h)),cx=x+w/2,cy=y+h/2,sx=Math.max(0,Math.min(c.width-side,cx-side/2)),sy=Math.max(0,Math.min(c.height-side,cy-side/2)),o=document.createElement('canvas');o.width=o.height=640;o.getContext('2d').drawImage(c,sx,sy,side,side,0,0,640,640);return o;}
  function extractCode(t){let m=t.match(/\b\d{4}[\s-]+\d{4}[\s-]+\d{4}\b/);if(m)return m[0].replace(/\D/g,'');m=t.match(/(?:^|\D)(\d{12})(?:\D|$)/);if(m)return m[1];for(const line of t.split(/[\r\n]+/)){const d=line.replace(/\D/g,'');if(d.length===12)return d;}return'';}
  async function detectQr(c){if('BarcodeDetector'in window)try{const d=new BarcodeDetector({formats:['qr_code']}),r=await d.detect(c);if(r.length)return{raw:r[0].rawValue||'',crop:qrCrop(c,r[0].boundingBox)};}catch(e){console.warn(e);}if(window.jsQR)try{const g=c.getContext('2d',{willReadFrequently:true}),im=g.getImageData(0,0,c.width,c.height),r=window.jsQR(im.data,c.width,c.height,{inversionAttempts:'attemptBoth'});if(r){const p=[r.location.topLeftCorner,r.location.topRightCorner,r.location.bottomLeftCorner,r.location.bottomRightCorner],x=Math.min(...p.map(q=>q.x)),X=Math.max(...p.map(q=>q.x)),y=Math.min(...p.map(q=>q.y)),Y=Math.max(...p.map(q=>q.y));return{raw:r.data||'',crop:qrCrop(c,{x,y,width:X-x,height:Y-y})};}}catch(e){console.warn(e);}return{raw:'',crop:null};}
  async function scanCode(){if(!S.codeImage||S.codeScanning)return;S.codeScanning=true;$('codeStatus').textContent='Scanning…';try{const c=canvasFrom(S.codeImage),q=await detectQr(c);S.qrCrop=q.crop;let code=extractCode(q.raw);if(!code){for(const psm of ['6','11']){const r=await read(c,psm,'0123456789 -');code=extractCode(r.text);if(code)break;}}if(code){$('trainerCode').value=formatCode(code);$('codeState').textContent='Detected';$('codeState').className='ok';}else{$('codeState').textContent='Review';$('codeState').className='review';}$('qrStatus').textContent=S.qrCrop?'QR detected':'QR needs review';$('qrStatus').className=S.qrCrop?'chip accent':'chip';$('codeStatus').textContent=code&&S.qrCrop?'Ready':'Review';drawAll();}catch(e){console.error(e);$('codeStatus').textContent='Review';toast('Trainer Code scan needs manual review.');}finally{S.codeScanning=false;}}

  async function handleProfile(file){if(!file)return;try{const {img,url}=await loadFile(file);revoke(S.sourceURL);S.sourceImage=img;S.sourceURL=url;$('thumb').src=url;$('sourceName').textContent=file.name;$('sourceMeta').textContent=fileMeta(file);$('sourceCard').classList.remove('hidden');$('cardEmpty').classList.add('hidden');$('ocrAgainBtn').disabled=false;$('saveBtn').disabled=false;setTeam(detectTeam(img),true,true);await scanProfile();}catch(e){console.error(e);toast('Could not read that screenshot.');}}
  async function handleArt(file,kind){if(!file)return;try{const {img,url}=await loadFile(file);if(kind==='trainer'){revoke(S.trainerURL);S.trainerImage=img;S.trainerURL=url;$('trainerThumb').src=url;$('trainerThumb').classList.remove('hidden');$('trainerEmpty').classList.add('hidden');}else{revoke(S.buddyURL);S.buddyImage=img;S.buddyURL=url;$('buddyThumb').src=url;$('buddyThumb').classList.remove('hidden');$('buddyEmpty').classList.add('hidden');}drawAll();}catch(e){console.error(e);toast('Could not load that image.');}}
  async function handleCode(file){if(!file)return;try{const {img,url}=await loadFile(file);revoke(S.codeURL);S.codeImage=img;S.codeURL=url;$('codeThumb').src=url;$('codeName').textContent=file.name;$('codeMeta').textContent=fileMeta(file);$('codeSourceCard').classList.remove('hidden');$('rescanCodeBtn').disabled=false;await scanCode();}catch(e){console.error(e);toast('Could not read that Trainer Code screenshot.');}}

  function bindRange(id,out,cb,fmt=v=>v){const input=$(id),output=$(out);const sync=()=>{const v=Number(input.value);output.textContent=fmt(v);cb(v);drawAll();};input.addEventListener('input',sync);sync();}
  function flip(){S.showBack=!S.showBack;$('cardFlipper').classList.toggle('flipped',S.showBack);$('sidePill').textContent=S.showBack?'Back':'Front';$('saveBtn').querySelector('small').textContent=`${S.showBack?'Back':'Front'} · PNG`;}
  function save(){drawAll();const c=S.showBack?$('backCanvas'):$('cardCanvas'),a=document.createElement('a'),name=($('trainerName').value||'trainer').replace(/\W+/g,'_');a.href=c.toDataURL('image/png');a.download=`${name}_${S.team}_custom_trainer_card_${S.showBack?'back':'front'}_v24.png`;a.click();toast(`${S.showBack?'Back':'Front'} card saved.`);}
  async function reset(){revoke(S.sourceURL);revoke(S.trainerURL);revoke(S.buddyURL);revoke(S.codeURL);S.sourceImage=S.trainerImage=S.buddyImage=S.codeImage=S.qrCrop=null;S.sourceURL=S.trainerURL=S.buddyURL=S.codeURL='';S.showBack=false;S.trainerPose={zoom:1,x:0,y:0};S.buddyPose={zoom:1,x:0,y:0};['trainerName','level','buddy','caught','stops','xp','startDate','trainerCode'].forEach(id=>{$(id).value='';setFieldState(id,'manual');});$('printDate').value=today();$('sourceCard').classList.add('hidden');$('codeSourceCard').classList.add('hidden');$('trainerThumb').classList.add('hidden');$('buddyThumb').classList.add('hidden');$('trainerEmpty').classList.remove('hidden');$('buddyEmpty').classList.remove('hidden');$('cardEmpty').classList.remove('hidden');$('ocrAgainBtn').disabled=true;$('rescanCodeBtn').disabled=true;$('saveBtn').disabled=true;$('cardFlipper').classList.remove('flipped');$('sidePill').textContent='Front';$('codeStatus').textContent='Waiting';$('qrStatus').textContent='Waiting';$('codeState').textContent='Manual';['trainerZoom','buddyZoom'].forEach(id=>$(id).value='1');['trainerX','trainerY','buddyX','buddyY'].forEach(id=>$(id).value='0');S.sat=76;S.light=48;$('sat').value='76';$('light').value='48';setTeam('valor',false,true);updateQuality();drawAll();toast('Reset complete.');}

  document.addEventListener('DOMContentLoaded',()=>{
    $('printDate').value=today();
    $('profileInput').addEventListener('change',e=>handleProfile(e.target.files?.[0]));$('replaceBtn').addEventListener('click',()=>$('profileInput').click());$('ocrAgainBtn').addEventListener('click',scanProfile);
    document.querySelectorAll('.team').forEach(b=>b.addEventListener('click',()=>setTeam(b.dataset.team,false,true)));
    ['trainerName','level','buddy','caught','stops','xp','startDate','printDate','trainerCode'].forEach(id=>$(id).addEventListener('input',()=>{if(id!=='printDate'&&id!=='trainerCode')setFieldState(id,'manual');updateQuality();drawAll();}));
    $('trainerImageInput').addEventListener('change',e=>handleArt(e.target.files?.[0],'trainer'));$('buddyImageInput').addEventListener('change',e=>handleArt(e.target.files?.[0],'buddy'));
    bindRange('trainerZoom','trainerZoomOut',v=>S.trainerPose.zoom=v,v=>v.toFixed(2)+'×');bindRange('trainerX','trainerXOut',v=>S.trainerPose.x=v,v=>v.toFixed(2));bindRange('trainerY','trainerYOut',v=>S.trainerPose.y=v,v=>v.toFixed(2));bindRange('buddyZoom','buddyZoomOut',v=>S.buddyPose.zoom=v,v=>v.toFixed(2)+'×');bindRange('buddyX','buddyXOut',v=>S.buddyPose.x=v,v=>v.toFixed(2));bindRange('buddyY','buddyYOut',v=>S.buddyPose.y=v,v=>v.toFixed(2));
    $('hue').addEventListener('input',()=>{S.hue=Number($('hue').value);syncTheme();});$('sat').addEventListener('input',()=>{S.sat=Number($('sat').value);syncTheme();});$('light').addEventListener('input',()=>{S.light=Number($('light').value);syncTheme();});$('resetColorBtn').addEventListener('click',()=>{S.hue=TEAM[S.team].hue;S.sat=76;S.light=48;$('hue').value=S.hue;$('sat').value='76';$('light').value='48';syncTheme();});
    $('codeInput').addEventListener('change',e=>handleCode(e.target.files?.[0]));$('replaceCodeBtn').addEventListener('click',()=>$('codeInput').click());$('rescanCodeBtn').addEventListener('click',scanCode);$('trainerCode').addEventListener('blur',()=>{$('trainerCode').value=formatCode($('trainerCode').value);drawAll();});
    $('flipBtn').addEventListener('click',flip);$('cardStage').addEventListener('click',flip);$('cardStage').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();flip();}});$('saveBtn').addEventListener('click',save);$('resetBtn').addEventListener('click',reset);
    setTeam('valor',false,true);syncTheme();updateQuality();drawAll();
  });
})();