(() => {
'use strict';
const $=id=>document.getElementById(id), kinds=['trainer','buddy','looking','favorite'];
const fresh=()=>({trainer:{cx:.5,cy:.44,w:.62,h:.72},buddy:{cx:.5,cy:.45,r:.31},looking:{cx:.5,cy:.5,r:.30},favorite:{cx:.5,cy:.5,r:.30}});
const state=fresh(), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function css(){if($('#tc32css'))return;const s=document.createElement('style');s.id='tc32css';s.textContent=`
.cropCanvasWrap{position:relative!important;touch-action:pan-y pinch-zoom!important;overscroll-behavior:auto!important}.cropCanvasWrap canvas{pointer-events:none!important;touch-action:pan-y pinch-zoom!important}.cropCanvasWrap.cropEditing{touch-action:none!important;outline:2px solid var(--accent);outline-offset:3px;border-radius:14px}.cropCanvasWrap.cropEditing canvas{pointer-events:none!important;touch-action:none!important}.tcLayer{position:absolute;inset:0;z-index:30;display:none;pointer-events:none}.cropEditing .tcLayer{display:block}.tcMove{position:absolute;transform:translate(-50%,-50%);pointer-events:auto;touch-action:none;border:2px dashed rgba(255,255,255,.7);background:rgba(255,255,255,.025);box-sizing:border-box}.tcMove.rect{border-radius:10px}.tcMove.circle{border-radius:50%}.tcMove:after{content:'DRAG TO MOVE';position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);padding:5px 8px;border-radius:999px;background:rgba(5,8,13,.8);color:#fff;font:900 9px/1 system-ui;white-space:nowrap;pointer-events:none}.tcH{position:absolute;z-index:35;width:64px;height:64px;margin:-32px 0 0 -32px;border:3px solid #fff;border-radius:50%;background:rgba(5,8,13,.97);color:#fff;display:grid;place-items:center;font:900 23px/1 system-ui;box-shadow:0 4px 18px rgba(0,0,0,.7),0 0 0 5px rgba(0,0,0,.25);pointer-events:auto;touch-action:none;user-select:none}.tcH.big{width:70px;height:70px;margin:-35px 0 0 -35px}.tcH:active{background:var(--accent);color:#080b10}.tcBadge{position:absolute;z-index:36;top:8px;left:8px;display:none;padding:6px 9px;border:1px solid var(--accent);border-radius:999px;background:rgba(5,8,13,.92);color:var(--accent2);font-size:9px;font-weight:900;pointer-events:none}.cropEditing .tcBadge{display:block}.cropModeBtn{min-height:50px!important}.cropAdjustBlock button{min-height:48px}
`;document.head.appendChild(s)}
function send(c,t,id,x,y){const ev=new PointerEvent(t,{bubbles:true,cancelable:true,pointerId:id,pointerType:'touch',isPrimary:true,clientX:x,clientY:y,button:0,buttons:t==='pointerup'?0:1,pressure:t==='pointerup'?0:.5});if(t==='pointerdown'&&c.setPointerCapture){const old=c.setPointerCapture;try{c.setPointerCapture=()=>{};c.dispatchEvent(ev)}finally{c.setPointerCapture=old}}else c.dispatchEvent(ev)}
function pt(c,x,y){const r=c.getBoundingClientRect();return{x:r.left+x*r.width,y:r.top+y*r.height}}
function geom(k){const c=$(k+'CropCanvas'),s=state[k];if(k==='trainer')return{cx:s.cx,cy:s.cy,w:s.w,h:s.h};const m=Math.min(c.width||1,c.height||1);return{cx:s.cx,cy:s.cy,rx:s.r*m/(c.width||1),ry:s.r*m/(c.height||1)}}
function paint(k){const g=geom(k),m=$(k+'Move');if(!g||!m)return;if(k==='trainer'){m.style.cssText+=`;left:${g.cx*100}%;top:${g.cy*100}%;width:${g.w*100}%;height:${g.h*100}%`;const w=$(k+'W'),h=$(k+'H'),b=$(k+'B');w.style.left=`${(g.cx+g.w/2)*100}%`;w.style.top=`${g.cy*100}%`;h.style.left=`${g.cx*100}%`;h.style.top=`${(g.cy+g.h/2)*100}%`;b.style.left=`${(g.cx+g.w/2)*100}%`;b.style.top=`${(g.cy+g.h/2)*100}%`}else{m.style.cssText+=`;left:${g.cx*100}%;top:${g.cy*100}%;width:${g.rx*200}%;height:${g.ry*200}%`;const r=$(k+'R');r.style.left=`${(g.cx+g.rx)*100}%`;r.style.top=`${g.cy*100}%`}}
function anchor(k,mode){const c=$(k+'CropCanvas'),s=state[k];if(k==='trainer'){if(mode==='move')return pt(c,s.cx,s.cy);if(mode==='w')return pt(c,s.cx+s.w/2,s.cy);if(mode==='h')return pt(c,s.cx,s.cy+s.h/2);return pt(c,s.cx+s.w/2,s.cy+s.h/2)}const m=Math.min(c.width||1,c.height||1),rx=s.r*m/(c.width||1);return mode==='move'?pt(c,s.cx,s.cy):pt(c,s.cx+rx,s.cy)}
function local(k,mode,start,dx,dy,rect,c){const s=state[k];if(k==='trainer'){if(mode==='move'){s.cx=clamp(start.cx+dx/rect.width,start.w/2,1-start.w/2);s.cy=clamp(start.cy+dy/rect.height,start.h/2,1-start.h/2)}else{if(mode==='w'||mode==='both')s.w=clamp(start.w+2*dx/rect.width,.18,.96);if(mode==='h'||mode==='both')s.h=clamp(start.h+2*dy/rect.height,.20,.96);s.cx=clamp(start.cx,s.w/2,1-s.w/2);s.cy=clamp(start.cy,s.h/2,1-s.h/2)}}else{const m=Math.min(c.width||1,c.height||1);if(mode==='move'){s.cx=start.cx+dx/rect.width;s.cy=start.cy+dy/rect.height;const rx=s.r*m/(c.width||1),ry=s.r*m/(c.height||1);s.cx=clamp(s.cx,rx,1-rx);s.cy=clamp(s.cy,ry,1-ry)}else{const ix=dx*(c.width||1)/rect.width;s.r=clamp(start.r+ix/m,.08,.48);const rx=s.r*m/(c.width||1),ry=s.r*m/(c.height||1);s.cx=clamp(start.cx,rx,1-rx);s.cy=clamp(start.cy,ry,1-ry)}}}
function drag(el,k,mode){el.addEventListener('pointerdown',e=>{const c=$(k+'CropCanvas'),wrap=c?.closest('.cropCanvasWrap');if(!c||!wrap?.classList.contains('cropEditing')||c.width<=1)return;e.preventDefault();e.stopPropagation();const id=e.pointerId||77,rect=c.getBoundingClientRect(),start={...state[k]},a=anchor(k,mode),sx=e.clientX,sy=e.clientY;el.setPointerCapture?.(e.pointerId);send(c,'pointerdown',id,a.x,a.y);const mv=q=>{const dx=q.clientX-sx,dy=q.clientY-sy;local(k,mode,start,dx,dy,rect,c);paint(k);send(c,'pointermove',id,a.x+dx,a.y+dy);scheduleApply(k);q.preventDefault()};const up=q=>{el.removeEventListener('pointermove',mv);el.removeEventListener('pointerup',up);el.removeEventListener('pointercancel',up);const dx=(q.clientX??sx)-sx,dy=(q.clientY??sy)-sy;send(c,'pointerup',id,a.x+dx,a.y+dy);scheduleApply(k,true);q.preventDefault()};el.addEventListener('pointermove',mv);el.addEventListener('pointerup',up);el.addEventListener('pointercancel',up)})}
function mode(k,on){const c=$(k+'CropCanvas'),w=c?.closest('.cropCanvasWrap'),b=$(k+'Mode'),h=$(k+'Help');if(!c||!w||!b)return;if(on&&c.width<=1){h.innerHTML='<strong>Upload a screenshot first.</strong>';return}kinds.forEach(x=>{if(x!==k&&$(x+'CropCanvas')?.closest('.cropCanvasWrap')?.classList.contains('cropEditing'))mode(x,false)});w.classList.toggle('cropEditing',on);b.classList.toggle('active',on);b.textContent=on?'Done adjusting':'Adjust crop';b.setAttribute('aria-pressed',on?'true':'false');h.innerHTML=on?'<strong>Adjust mode:</strong> drag the crop controls. Swipe elsewhere on the screenshot to scroll.':'<strong>Scroll mode:</strong> swipe directly over the screenshot to scroll the page.';paint(k);syncSticky(k)}
function layer(k){const c=$(k+'CropCanvas'),w=c?.closest('.cropCanvasWrap');if(!c||!w)return;const badge=document.createElement('div');badge.className='tcBadge';badge.textContent='ADJUST MODE';w.appendChild(badge);const l=document.createElement('div');l.className='tcLayer';l.id=k+'Layer';if(k==='trainer')l.innerHTML=`<div id="${k}Move" class="tcMove rect"></div><button id="${k}W" class="tcH" type="button">↔</button><button id="${k}H" class="tcH" type="button">↕</button><button id="${k}B" class="tcH big" type="button">↘</button>`;else l.innerHTML=`<div id="${k}Move" class="tcMove circle"></div><button id="${k}R" class="tcH big" type="button">↔</button>`;w.appendChild(l);drag($(k+'Move'),k,'move');if(k==='trainer'){drag($(k+'W'),k,'w');drag($(k+'H'),k,'h');drag($(k+'B'),k,'both')}else drag($(k+'R'),k,'r');paint(k)}
function controls(k){const c=$(k+'CropCanvas'),w=c?.closest('.cropCanvasWrap');if(!c||!w)return;const bar=document.createElement('div');bar.className='cropModeBar';bar.innerHTML=`<button id="${k}Mode" class="cropModeBtn" type="button" aria-pressed="false">Adjust crop</button><div id="${k}Help" class="cropModeHelp"><strong>Scroll mode:</strong> swipe directly over the screenshot to scroll the page.</div>`;w.insertAdjacentElement('afterend',bar);$(k+'Mode').onclick=()=>mode(k,!w.classList.contains('cropEditing'));$(k+'ShotInput')?.addEventListener('change',()=>{Object.assign(state[k],fresh()[k]);mode(k,false);setTimeout(()=>{paint(k);scheduleApply(k,true);renderPreview(k)},120)})}

const applyTimers={};
function scheduleApply(k,now=false){clearTimeout(applyTimers[k]);applyTimers[k]=setTimeout(()=>{$(k+'ApplyCrop')?.click();setTimeout(()=>renderPreview(k),0)},now?0:90)}
function ready(img){return !!(img&&img.src&&img.complete&&img.naturalWidth>0)}
function previewSource(k){const full=$(k+'UseFull'),src=$(k+'SourceThumb'),res=$(k+'Result');if(full?.checked&&ready(src))return src;if(ready(res)&&!res.classList.contains('hidden'))return res;return ready(src)?src:null}
function rounded(g,x,y,w,h,r){g.beginPath();g.roundRect(x,y,w,h,r)}
function cover(g,img,w,h,z){const iw=img.naturalWidth,ih=img.naturalHeight,base=Math.max(w/iw,h/ih),s=base*z,dw=iw*s,dh=ih*s;g.drawImage(img,(w-dw)/2,(h-dh)/2,dw,dh)}
function renderPreview(k){const cv=$(k+'LocalPreviewCanvas');if(!cv)return;const trainer=k==='trainer';let w=420,h=420;if(trainer){const fw=Number($('trainerFrameW')?.value||520),fh=Number($('trainerFrameH')?.value||560);h=Math.max(220,Math.round(w*fh/fw));const sh=$(k+'LocalPreviewShape');if(sh)sh.style.aspectRatio=`${fw}/${fh}`}
cv.width=w;cv.height=h;const g=cv.getContext('2d');g.clearRect(0,0,w,h);g.fillStyle='#070b11';g.fillRect(0,0,w,h);g.save();if(trainer){rounded(g,0,0,w,h,24);g.clip()}else{g.beginPath();g.arc(w/2,h/2,Math.min(w,h)/2,0,Math.PI*2);g.clip()}const img=previewSource(k),z=Math.max(.25,Math.min(2,Number($(k+'Zoom')?.value||1)));if(img)cover(g,img,w,h,z);else{g.fillStyle='#0d1520';g.fillRect(0,0,w,h);g.fillStyle='rgba(255,255,255,.45)';g.textAlign='center';g.textBaseline='middle';g.font='800 24px system-ui';g.fillText('UPLOAD SCREENSHOT',w/2,h/2)}g.restore();g.strokeStyle=getComputedStyle(document.documentElement).getPropertyValue('--accent2').trim()||'#fff';g.lineWidth=7;if(trainer){rounded(g,4,4,w-8,h-8,22);g.stroke()}else{g.beginPath();g.arc(w/2,h/2,Math.min(w,h)/2-4,0,Math.PI*2);g.stroke()}const out=$(k+'LocalZoomOut');if(out)out.textContent=z.toFixed(2)+'×'}
function buildPreview(k){const bar=$(k+'Mode')?.closest('.cropModeBar'),host=$(k+'CropCanvas')?.closest('.cropCard,.optionalCard');if(!bar||!host||$(k+'LocalPreview'))return;const trainer=k==='trainer',box=document.createElement('div');box.id=k+'LocalPreview';box.className='localSlotPreview';box.innerHTML=`<div class="localPreviewHead"><b>Card slot preview</b><span id="${k}LocalZoomOut">1.00×</span></div><div class="localPreviewStage"><div id="${k}LocalPreviewShape" class="localPreviewShape ${trainer?'trainer':'circle'}"><canvas id="${k}LocalPreviewCanvas"></canvas></div></div><label class="localZoomLabel"><span>Zoom</span><input id="${k}LocalZoom" type="range" min="0.25" max="2" value="${$(k+'Zoom')?.value||1}" step="0.05"></label><small>This is how this image slot will look on the finished card.</small>`;bar.insertAdjacentElement('afterend',box);const local=$(k+'LocalZoom'),orig=$(k+'Zoom');local?.addEventListener('input',()=>{if(orig){orig.value=local.value;orig.dispatchEvent(new Event('input',{bubbles:true}))}renderPreview(k)});orig?.addEventListener('input',()=>{if(local)local.value=orig.value;renderPreview(k)});$(k+'UseFull')?.addEventListener('change',()=>renderPreview(k));$(k+'Result')?.addEventListener('load',()=>renderPreview(k));$(k+'SourceThumb')?.addEventListener('load',()=>renderPreview(k));if(trainer){$('trainerFrameW')?.addEventListener('input',()=>renderPreview(k));$('trainerFrameH')?.addEventListener('input',()=>renderPreview(k))}renderPreview(k)}
function syncSticky(k){const p=$(k+'LocalPreview'),wrap=$(k+'CropCanvas')?.closest('.cropCanvasWrap');p?.classList.toggle('editing',!!wrap?.classList.contains('cropEditing'))}
function previewCss(){if($('#localPreviewCss'))return;const s=document.createElement('style');s.id='localPreviewCss';s.textContent=`
.cropAdjustBlock{display:none!important}.cropResult{display:none!important}.localSlotPreview{margin:9px 0 10px;padding:10px;border:1px solid var(--line);border-radius:14px;background:rgba(7,11,17,.97);box-shadow:0 8px 24px rgba(0,0,0,.28)}.localPreviewHead{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:8px}.localPreviewHead b{font-size:11px}.localPreviewHead span{font-size:10px;font-weight:900;color:var(--accent2)}.localPreviewStage{display:grid;place-items:center;min-height:160px;padding:8px;border:1px solid rgba(255,255,255,.07);border-radius:12px;background:#05080d;overflow:hidden}.localPreviewShape{overflow:hidden;background:#05080d;box-shadow:0 8px 22px rgba(0,0,0,.35)}.localPreviewShape.trainer{width:min(58vw,220px);border-radius:13px}.localPreviewShape.circle{width:min(48vw,180px);aspect-ratio:1;border-radius:50%}.localPreviewShape canvas{display:block;width:100%;height:100%}.localZoomLabel{display:grid;grid-template-columns:auto 1fr;align-items:center;gap:10px;margin-top:9px;font-size:10px;font-weight:800}.localZoomLabel input{width:100%}.localSlotPreview>small{display:block;margin-top:6px;color:var(--muted);font-size:8px;line-height:1.35}.localSlotPreview.editing{position:sticky;bottom:8px;z-index:24;border-color:var(--accent);box-shadow:0 12px 34px rgba(0,0,0,.55)}@media(min-width:700px){.localPreviewShape.trainer{width:220px}.localPreviewShape.circle{width:180px}}`;document.head.appendChild(s)}
function init(){css();previewCss();kinds.forEach(k=>{controls(k);layer(k);buildPreview(k)});$('resetBtn')?.addEventListener('click',()=>{const d=fresh();kinds.forEach(k=>{Object.assign(state[k],d[k]);mode(k,false);paint(k);setTimeout(()=>renderPreview(k),0)})})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();