(() => {
'use strict';
const $=id=>document.getElementById(id);
const TEAM={
  valor:{name:'Valor',accent:'#ff4052',accent2:'#ff9a7a',dark:'#250b14'},
  mystic:{name:'Mystic',accent:'#2aa8ff',accent2:'#91ecff',dark:'#061c31'},
  instinct:{name:'Instinct',accent:'#f2c91f',accent2:'#fff18b',dark:'#2b2400'}
};
const S={
  team:'valor', infoImage:null,infoURL:'', codeImage:null,codeURL:'',qrCrop:null,ocr:null,scanning:false,showBack:false,drag:null,
  sources:{trainer:null,buddy:null,looking:null,favorite:null}, urls:{trainer:'',buddy:'',looking:'',favorite:''},
  crops:{trainer:{cx:.5,cy:.44,w:.62,h:.72},buddy:{cx:.5,cy:.45,r:.31},looking:{cx:.5,cy:.5,r:.30},favorite:{cx:.5,cy:.5,r:.30}},
  outputs:{trainer:null,buddy:null,looking:null,favorite:null}, frame:{w:520,h:560}, slotZoom:{trainer:1,buddy:1,looking:1,favorite:1}, slotUseFull:{trainer:false,buddy:false,looking:false,favorite:false}, backgrounds:{shared:null,front:null,back:null}, bgURLs:{shared:'',front:'',back:''}
};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const revoke=u=>{if(u)URL.revokeObjectURL(u);};
const today=()=>new Date().toLocaleDateString('en-US',{month:'numeric',day:'numeric',year:'numeric'});
const meta=f=>`${Math.round(f.size/1024)} KB · ${f.type||'image'}`;
const norm=s=>(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');
const fmtNum=d=>d.replace(/\B(?=(\d{3})+(?!\d))/g,',');
const cleanDate=t=>(t.match(/\b\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4}\b/)||[])[0]||'';
const toast=msg=>{const t=$('toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),2600);};
const loadFile=file=>new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>resolve({img,url});img.onerror=e=>{URL.revokeObjectURL(url);reject(e);};img.src=url;});
function setTheme(){const p=TEAM[S.team];document.documentElement.style.setProperty('--accent',p.accent);document.documentElement.style.setProperty('--accent2',p.accent2);}
function setState(id,state){const e=$(id+'State');if(!e)return;e.textContent=state==='ok'?'Detected':state==='review'?'Review':'Manual';e.className=state==='ok'?'ok':state==='review'?'review':'';}
function updateQuality(){const ids=['trainerName','level','buddy','caught','stops','xp','startDate'];const n=ids.filter(id=>($(id)?.value||'').trim()).length;$('qualityText').textContent=`${Math.round(n/ids.length*100)}%`;}
function setTeam(team,detected=false){if(!TEAM[team])return;S.team=team;setTheme();document.querySelectorAll('.team').forEach(b=>b.classList.toggle('active',b.dataset.team===team));$('teamStatus').textContent=`${detected?'Detected':'Selected'}: ${TEAM[team].name}`;$('previewTeam').textContent=TEAM[team].name;drawAll();}
function detectTeam(img){const c=document.createElement('canvas');c.width=220;c.height=330;const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(img,0,0,c.width,c.height);const d=g.getImageData(0,0,c.width,c.height).data;let R=0,B=0,Y=0;for(let i=0;i<d.length;i+=20){const r=d[i],gg=d[i+1],b=d[i+2],mx=Math.max(r,gg,b),mn=Math.min(r,gg,b);if(mx-mn<22)continue;R+=Math.max(0,r-(gg+b)/2);B+=Math.max(0,b-(r+gg)/2);Y+=Math.max(0,Math.min(r,gg)-b*.72);}return Object.entries({valor:R,mystic:B,instinct:Y}).sort((a,b)=>b[1]-a[1])[0][0];}

async function worker(){if(!S.ocr)S.ocr=await Tesseract.createWorker('eng',1,{logger:m=>{if(m.status==='recognizing text'&&$('scanPct'))$('scanPct').textContent=`${Math.round((m.progress||0)*100)}%`;}});return S.ocr;}
async function read(c,psm='7',whitelist=''){const w=await worker();await w.setParameters({tessedit_pageseg_mode:psm,...(whitelist?{tessedit_char_whitelist:whitelist}:{})});const r=await w.recognize(c);return{text:r.data.text||'',confidence:r.data.confidence||0};}
function ocrCrop(img,x,y,w,h,scale=7,mode='normal'){const iw=img.naturalWidth||img.width,ih=img.naturalHeight||img.height,c=document.createElement('canvas');c.width=Math.max(1,Math.round(iw*w*scale));c.height=Math.max(1,Math.round(ih*h*scale));const g=c.getContext('2d',{willReadFrequently:true});g.imageSmoothingEnabled=true;g.imageSmoothingQuality='high';g.drawImage(img,iw*x,ih*y,iw*w,ih*h,0,0,c.width,c.height);if(mode!=='normal'){const im=g.getImageData(0,0,c.width,c.height),d=im.data;for(let i=0;i<d.length;i+=4){const r=d[i],gg=d[i+1],b=d[i+2];let hit=false;if(mode==='maroon')hit=r>72&&r>gg*1.16&&r>b*1.06&&gg<190;if(mode==='green')hit=gg>82&&gg>r*1.03&&gg>b*.86;if(mode==='red')hit=r>92&&r>gg*1.10&&r>b*1.02;if(mode==='dark')hit=(r+gg+b)<440;const v=hit?0:255;d[i]=d[i+1]=d[i+2]=v;d[i+3]=255;}g.putImageData(im,0,0);}return c;}
function textTokens(text,allowDigits=true){const out=[];for(const line of (text||'').split(/[\r\n]+/)){const compact=line.replace(allowDigits?/[^A-Za-z0-9_-]/g:/[^A-Za-z-]/g,'').replace(/^[_-]+|[_-]+$/g,'');if(compact.length>=2&&compact.length<=28)out.push(compact);const re=allowDigits?/[A-Za-z][A-Za-z0-9_-]{1,27}/g:/[A-Za-z][A-Za-z-]{1,27}/g;out.push(...(line.match(re)||[]));}return[...new Set(out.filter(Boolean))];}
function literalConsensus(reads,{allowDigits=true,blocked=[]}={}){const stop=new Set(blocked.map(norm)),groups=new Map();for(const r of reads){for(const t of textTokens(r.text,allowDigits)){const k=norm(t);if(!k||stop.has(k)||/^\d+$/.test(t))continue;const g=groups.get(k)||{value:t,count:0,total:0,max:0};g.count++;g.total+=Number(r.confidence||0);g.max=Math.max(g.max,Number(r.confidence||0));if(t.length>g.value.length)g.value=t;groups.set(k,g);}}let best=null;for(const g of groups.values()){g.avg=g.total/g.count;g.score=g.count*70+g.avg+Math.min(g.value.length,18);if(!best||g.score>best.score)best=g;}return best||{value:'',count:0,max:0};}
function numberFrom(text){const ms=(text||'').match(/[\d][\d,\.\s]*/g)||[],ds=ms.map(s=>s.replace(/\D/g,'')).filter(Boolean);return ds.sort((a,b)=>b.length-a.length)[0]||'';}
function consensusNumber(reads,{minDigits=1,maxDigits=12,maxValue=Number.MAX_SAFE_INTEGER}={}){const m=new Map();for(const r of reads){const d=numberFrom(r.text);if(!d||d.length<minDigits||d.length>maxDigits||Number(d)>maxValue)continue;const v=m.get(d)||{digits:d,count:0,confidence:0};v.count++;v.confidence=Math.max(v.confidence,r.confidence||0);m.set(d,v);}return[...m.values()].sort((a,b)=>b.count-a.count||b.confidence-a.confidence)[0]||null;}
function consensusDate(reads){const m=new Map();for(const r of reads){const d=cleanDate(r.text);if(!d)continue;const v=m.get(d)||{value:d,count:0,confidence:0};v.count++;v.confidence=Math.max(v.confidence,r.confidence||0);m.set(d,v);}return[...m.values()].sort((a,b)=>b.count-a.count||b.confidence-a.confidence)[0]||null;}
async function readSet(normal,masked,whitelist){return[await read(normal,'7',whitelist),await read(masked,'7',whitelist),await read(normal,'6',whitelist),await read(masked,'13',whitelist)];}
async function scanInfo(){if(!S.infoImage||S.scanning)return;S.scanning=true;$('scanCard').classList.remove('hidden');$('scanPct').textContent='0%';try{setTeam(detectTeam(S.infoImage),true);$('scanTitle').textContent='Reading information screenshot';let normal,mask,reads,pick;$('scanDetail').textContent='Trainer name';normal=ocrCrop(S.infoImage,.045,.126,.40,.038,7);mask=ocrCrop(S.infoImage,.045,.126,.40,.038,7,'maroon');reads=await readSet(normal,mask,'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-');pick=literalConsensus(reads,{allowDigits:true,blocked:['me','friends','social','level','buddy','history','scrapbook','journal','style','total','activity']});if(pick.value){$('trainerName').value=pick.value;setState('trainerName',pick.count>=2||pick.max>=72?'ok':'review');}else setState('trainerName','review');$('scanDetail').textContent='Buddy name';normal=ocrCrop(S.infoImage,.045,.151,.40,.036,8);mask=ocrCrop(S.infoImage,.045,.151,.40,.036,8,'maroon');reads=await readSet(normal,mask,'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-');pick=literalConsensus(reads,{allowDigits:false,blocked:['buddy','history','scrapbook','journal','style','friends','social','me','mega','cp',$('trainerName').value]});if(pick.value){$('buddy').value=pick.value;setState('buddy',pick.count>=2||pick.max>=72?'ok':'review');}else setState('buddy','review');const jobs=[['level','Level',[.055,.526,.16,.050],'red','0123456789',{minDigits:1,maxDigits:3,maxValue:100}],['caught','Pokémon caught',[.585,.792,.30,.035],'green','0123456789,',{minDigits:2,maxDigits:9}],['stops','PokéStops visited',[.585,.831,.30,.035],'green','0123456789,',{minDigits:2,maxDigits:9}],['xp','Total XP',[.585,.870,.36,.035],'green','0123456789,',{minDigits:4,maxDigits:12}],['startDate','Start date',[.585,.909,.30,.035],'green','0123456789/-',null]];for(const[id,label,r,mode,white,rules]of jobs){$('scanDetail').textContent=label;normal=ocrCrop(S.infoImage,...r,6);mask=ocrCrop(S.infoImage,...r,6,mode);reads=await readSet(normal,mask,white);if(id==='startDate'){const p=consensusDate(reads);if(p){$(id).value=p.value;setState(id,p.count>=2?'ok':'review');}else setState(id,'review');}else{const p=consensusNumber(reads,rules||{});if(p){$(id).value=id==='level'?String(Number(p.digits)):fmtNum(p.digits);setState(id,p.count>=2?'ok':'review');}else setState(id,'review');}}updateQuality();drawAll();toast('OCR filled what it could. Review anything marked Review.');}catch(e){console.error(e);toast('OCR could not finish. You can still enter every field manually.');}finally{S.scanning=false;$('scanCard').classList.add('hidden');}}

function setupCropCanvas(kind){const c=$(kind+'CropCanvas'),src=S.sources[kind];if(!c||!src)return;const sw=src.naturalWidth||src.width,sh=src.naturalHeight||src.height,maxW=Math.min(900,sw),ratio=sh/sw;c.width=Math.max(1,Math.round(maxW));c.height=Math.max(1,Math.round(maxW*ratio));$(kind+'CropEmpty')?.classList.add('hidden');drawCropEditor(kind);}
function cropPixels(kind){const src=S.sources[kind];if(!src)return null;const iw=src.naturalWidth||src.width,ih=src.naturalHeight||src.height,s=S.crops[kind];if(kind==='trainer'){const w=s.w*iw,h=s.h*ih,cx=s.cx*iw,cy=s.cy*ih;return{x:clamp(cx-w/2,0,iw-w),y:clamp(cy-h/2,0,ih-h),w,h};}const r=s.r*Math.min(iw,ih),cx=s.cx*iw,cy=s.cy*ih;return{x:clamp(cx-r,0,iw-2*r),y:clamp(cy-r,0,ih-2*r),w:2*r,h:2*r};}
function drawCropEditor(kind){const c=$(kind+'CropCanvas'),src=S.sources[kind];if(!c||!src)return;const g=c.getContext('2d'),s=S.crops[kind];g.clearRect(0,0,c.width,c.height);g.drawImage(src,0,0,c.width,c.height);g.fillStyle='rgba(0,0,0,.50)';g.fillRect(0,0,c.width,c.height);g.save();g.strokeStyle='#fff';g.lineWidth=Math.max(3,c.width/250);g.fillStyle='#fff';g.font=`900 ${Math.max(13,c.width/46)}px system-ui`;if(kind==='trainer'){const x=(s.cx-s.w/2)*c.width,y=(s.cy-s.h/2)*c.height,w=s.w*c.width,h=s.h*c.height;g.beginPath();g.rect(x,y,w,h);g.clip();g.drawImage(src,0,0,c.width,c.height);g.restore();g.strokeStyle='#fff';g.lineWidth=Math.max(3,c.width/250);g.strokeRect(x,y,w,h);const hs=Math.max(13,c.width/58);g.fillStyle='#fff';g.fillRect(x+w-hs/2,y+h/2-hs/2,hs,hs);g.fillRect(x+w/2-hs/2,y+h-hs/2,hs,hs);g.fillRect(x+w-hs/2,y+h-hs/2,hs,hs);g.font=`900 ${Math.max(13,c.width/46)}px system-ui`;g.fillText('TRAINER CROP',x+9,y+Math.max(21,c.width/32));}else{const min=Math.min(c.width,c.height),r=s.r*min,cx=s.cx*c.width,cy=s.cy*c.height;g.beginPath();g.arc(cx,cy,r,0,Math.PI*2);g.clip();g.drawImage(src,0,0,c.width,c.height);g.restore();g.strokeStyle='#fff';g.lineWidth=Math.max(3,c.width/250);g.beginPath();g.arc(cx,cy,r,0,Math.PI*2);g.stroke();const hs=Math.max(13,c.width/58);g.fillStyle='#fff';g.beginPath();g.arc(cx+r,cy,hs*.62,0,Math.PI*2);g.fill();g.font=`900 ${Math.max(13,c.width/46)}px system-ui`;g.fillText(kind==='buddy'?'BUDDY CIRCLE':kind==='looking'?'LOOKING FOR':'FAVORITE',cx-r+8,cy-r+Math.max(21,c.width/32));}}
function editorPoint(e,c){const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height};}
function pointerDown(kind,e){const c=$(kind+'CropCanvas'),q=editorPoint(e,c),s=S.crops[kind],handle=Math.max(30,c.width/30);if(kind==='trainer'){const x=(s.cx-s.w/2)*c.width,y=(s.cy-s.h/2)*c.height,w=s.w*c.width,h=s.h*c.height;const right={x:x+w,y:y+h/2},bottom={x:x+w/2,y:y+h},corner={x:x+w,y:y+h};if(Math.hypot(q.x-corner.x,q.y-corner.y)<handle)S.drag={kind,mode:'resizeBoth',sx:q.x,sy:q.y,start:{...s}};else if(Math.hypot(q.x-right.x,q.y-right.y)<handle)S.drag={kind,mode:'resizeW',sx:q.x,sy:q.y,start:{...s}};else if(Math.hypot(q.x-bottom.x,q.y-bottom.y)<handle)S.drag={kind,mode:'resizeH',sx:q.x,sy:q.y,start:{...s}};else if(q.x>=x&&q.x<=x+w&&q.y>=y&&q.y<=y+h)S.drag={kind,mode:'move',sx:q.x,sy:q.y,start:{...s}};}else{const min=Math.min(c.width,c.height),r=s.r*min,cx=s.cx*c.width,cy=s.cy*c.height;if(Math.hypot(q.x-(cx+r),q.y-cy)<handle)S.drag={kind,mode:'resize',sx:q.x,sy:q.y,start:{...s}};else if(Math.hypot(q.x-cx,q.y-cy)<=r)S.drag={kind,mode:'move',sx:q.x,sy:q.y,start:{...s}};}if(S.drag){c.setPointerCapture?.(e.pointerId);e.preventDefault();}}
function pointerMove(kind,e){if(!S.drag||S.drag.kind!==kind)return;const c=$(kind+'CropCanvas'),q=editorPoint(e,c),d=S.drag,s=S.crops[kind];if(kind==='trainer'){if(d.mode==='move'){s.cx=clamp(d.start.cx+(q.x-d.sx)/c.width,d.start.w/2,1-d.start.w/2);s.cy=clamp(d.start.cy+(q.y-d.sy)/c.height,d.start.h/2,1-d.start.h/2);}else{if(d.mode==='resizeW'||d.mode==='resizeBoth')s.w=clamp(d.start.w+2*(q.x-d.sx)/c.width,.18,.96);if(d.mode==='resizeH'||d.mode==='resizeBoth')s.h=clamp(d.start.h+2*(q.y-d.sy)/c.height,.20,.96);s.cx=clamp(s.cx,s.w/2,1-s.w/2);s.cy=clamp(s.cy,s.h/2,1-s.h/2);}}else{const min=Math.min(c.width,c.height);if(d.mode==='move'){s.cx=clamp(d.start.cx+(q.x-d.sx)/c.width,.05,.95);s.cy=clamp(d.start.cy+(q.y-d.sy)/c.height,.05,.95);}else s.r=clamp(d.start.r+(q.x-d.sx)/min,.08,.48);const rx=s.r*min/c.width,ry=s.r*min/c.height;s.cx=clamp(s.cx,rx,1-rx);s.cy=clamp(s.cy,ry,1-ry);}drawCropEditor(kind);}
function pointerUp(){S.drag=null;}
function applyCrop(kind){const src=S.sources[kind],p=cropPixels(kind);if(!src||!p)return;let out,g;if(kind==='trainer'){const max=900,ratio=p.h/p.w;out=document.createElement('canvas');out.width=max;out.height=Math.max(1,Math.round(max*ratio));g=out.getContext('2d');g.imageSmoothingEnabled=true;g.imageSmoothingQuality='high';g.drawImage(src,p.x,p.y,p.w,p.h,0,0,out.width,out.height);}else{const size=700;out=document.createElement('canvas');out.width=out.height=size;g=out.getContext('2d');g.save();g.beginPath();g.arc(size/2,size/2,size/2,0,Math.PI*2);g.clip();g.drawImage(src,p.x,p.y,p.w,p.h,0,0,size,size);g.restore();}S.outputs[kind]=out;const img=$(kind+'Result');if(img){img.src=out.toDataURL('image/png');img.classList.remove('hidden');}const txt=$(kind+'ResultText');if(txt)txt.textContent=kind==='trainer'?'Rectangular crop ready.':kind==='buddy'?'Buddy circle ready.':kind==='looking'?'Looking For circle ready.':'Favorite Pokémon circle ready.';drawAll();}
async function handleImageKind(kind,file){if(!file)return;try{const {img,url}=await loadFile(file);revoke(S.urls[kind]);S.urls[kind]=url;S.sources[kind]=img;S.outputs[kind]=null;const thumb=$(kind+'SourceThumb'),name=$(kind+'SourceName'),m=$(kind+'SourceMeta');if(thumb)thumb.src=url;if(name)name.textContent=file.name;if(m)m.textContent=meta(file);$(kind+'SourceCard')?.classList.remove('hidden');setupCropCanvas(kind);drawAll();}catch(e){console.error(e);toast(`Could not open the ${kind} screenshot.`);}}

function rr(g,x,y,w,h,r){g.beginPath();g.roundRect(x,y,w,h,r);}
function fitText(g,text,x,y,maxW,maxSize,weight=900,align='left'){let s=maxSize;g.textAlign=align;g.textBaseline='middle';while(s>13){g.font=`${weight} ${s}px system-ui,-apple-system,Segoe UI,sans-serif`;if(g.measureText(text).width<=maxW)break;s--;}g.fillText(text,x,y,maxW);}
function cover(g,img,x,y,w,h,r=0){if(!img)return false;const iw=img.width||img.naturalWidth,ih=img.height||img.naturalHeight;if(!iw||!ih)return false;const sc=Math.max(w/iw,h/ih),sw=w/sc,sh=h/sc,sx=(iw-sw)/2,sy=(ih-sh)/2;g.save();if(r){rr(g,x,y,w,h,r);g.clip();}g.drawImage(img,sx,sy,sw,sh,x,y,w,h);g.restore();return true;}
function slotImage(g,img,x,y,w,h,zoom=1,r=0){if(!img)return false;const iw=img.naturalWidth||img.width,ih=img.naturalHeight||img.height;if(!iw||!ih)return false;const base=Math.max(w/iw,h/ih),sc=base*zoom,dw=iw*sc,dh=ih*sc,dx=x+(w-dw)/2,dy=y+(h-dh)/2;g.save();if(r){rr(g,x,y,w,h,r);g.clip();}g.fillStyle='rgba(3,6,10,.82)';g.fillRect(x,y,w,h);g.drawImage(img,dx,dy,dw,dh);g.restore();return true;}
function chosenImage(kind){return S.slotUseFull[kind]?(S.sources[kind]||S.outputs[kind]):(S.outputs[kind]||S.sources[kind]);}
function circleImage(g,img,cx,cy,r,zoom=1){g.save();g.beginPath();g.arc(cx,cy,r,0,Math.PI*2);g.clip();g.fillStyle='rgba(3,6,10,.82)';g.fillRect(cx-r,cy-r,r*2,r*2);if(img)slotImage(g,img,cx-r,cy-r,r*2,r*2,zoom,0);g.restore();g.strokeStyle='rgba(255,255,255,.75)';g.lineWidth=3;g.beginPath();g.arc(cx,cy,r,0,Math.PI*2);g.stroke();}
function drawBackdrop(g,p,side){const custom=S.backgrounds[side]||S.backgrounds.shared;if(custom){cover(g,custom,0,0,900,1400,0);g.fillStyle='rgba(3,6,11,.22)';g.fillRect(0,0,900,1400);}else{const gr=g.createLinearGradient(0,0,900,1400);gr.addColorStop(0,p.dark);gr.addColorStop(.42,'#101725');gr.addColorStop(1,'#070a10');g.fillStyle=gr;g.fillRect(0,0,900,1400);g.globalAlpha=.16;g.strokeStyle=p.accent2;g.lineWidth=2;for(let i=-300;i<1300;i+=90){g.beginPath();g.moveTo(i,0);g.lineTo(i+700,1400);g.stroke();}g.globalAlpha=1;}g.strokeStyle=p.accent;g.lineWidth=8;rr(g,18,18,864,1364,34);g.stroke();g.strokeStyle='rgba(255,255,255,.22)';g.lineWidth=2;rr(g,31,31,838,1338,27);g.stroke();}
function label(g,text,x,y){g.fillStyle='rgba(255,255,255,.72)';g.font='800 18px system-ui';g.textAlign='left';g.textBaseline='middle';g.fillText(text.toUpperCase(),x,y);}
function value(g,text,x,y,maxW,size=34,align='left'){g.fillStyle='#fff';fitText(g,text||'—',x,y,maxW,size,900,align);}
function drawFront(){const c=$('cardCanvas'),g=c.getContext('2d'),p=TEAM[S.team];g.clearRect(0,0,c.width,c.height);drawBackdrop(g,p,'front');g.fillStyle=p.accent2;g.font='900 22px system-ui';g.textAlign='left';g.fillText('TRAINER CARD',64,76);g.textAlign='right';g.fillStyle=p.accent;g.font='950 24px system-ui';g.fillText(p.name.toUpperCase(),836,76);g.textAlign='left';g.fillStyle='#fff';fitText(g,($('trainerName').value||'TRAINER').trim(),64,136,600,58,950);g.fillStyle='rgba(5,8,13,.72)';rr(g,650,102,186,84,18);g.fill();label(g,'Level',674,124);value(g,($('level').value||'—').trim(),674,158,138,35);
  const fw=S.frame.w,fh=S.frame.h,fx=(900-fw)/2,fy=230;g.fillStyle='rgba(0,0,0,.33)';rr(g,fx-8,fy-8,fw+16,fh+16,26);g.fill();g.strokeStyle=p.accent2;g.lineWidth=3;rr(g,fx-8,fy-8,fw+16,fh+16,26);g.stroke();if(!slotImage(g,chosenImage('trainer'),fx,fy,fw,fh,S.slotZoom.trainer,20)){g.fillStyle='rgba(255,255,255,.04)';rr(g,fx,fy,fw,fh,20);g.fill();g.fillStyle='rgba(255,255,255,.55)';g.font='800 24px system-ui';g.textAlign='center';g.fillText('TRAINER IMAGE',450,fy+fh/2);}
  const br=108,bcx=748,bcy=360;g.fillStyle='rgba(4,6,10,.72)';g.beginPath();g.arc(bcx,bcy,br+10,0,Math.PI*2);g.fill();circleImage(g,chosenImage('buddy'),bcx,bcy,br,S.slotZoom.buddy);g.fillStyle=p.accent2;g.textAlign='center';g.font='800 17px system-ui';g.fillText('BUDDY',bcx,bcy+br+28);g.fillStyle='#fff';fitText(g,($('buddy').value||'—').trim(),bcx,bcy+br+57,230,27,900,'center');
  const sy=875;g.fillStyle='rgba(5,8,13,.78)';rr(g,55,sy,790,175,24);g.fill();g.strokeStyle='rgba(255,255,255,.14)';g.lineWidth=2;rr(g,55,sy,790,175,24);g.stroke();const cols=[['POKÉMON CAUGHT',$('caught').value,188],['POKÉSTOPS VISITED',$('stops').value,450],['TOTAL XP',$('xp').value,712]];for(const [lab,valv,x] of cols){g.fillStyle='rgba(255,255,255,.62)';g.font='800 15px system-ui';g.textAlign='center';g.fillText(lab,x,918);g.fillStyle='#fff';fitText(g,(valv||'—').trim(),x,972,210,34,950,'center');}
  g.fillStyle='rgba(5,8,13,.70)';rr(g,55,1070,790,248,24);g.fill();const show=[{img:chosenImage('looking'),zoom:S.slotZoom.looking,name:($('lookingName').value||'').trim(),label:'LOOKING FOR',x:250},{img:chosenImage('favorite'),zoom:S.slotZoom.favorite,name:($('favoriteName').value||'').trim(),label:'FAVORITE POKÉMON',x:650}];for(const it of show){g.fillStyle=p.accent2;g.font='900 17px system-ui';g.textAlign='center';g.fillText(it.label,it.x,1103);circleImage(g,it.img,it.x,1193,82,it.zoom);g.fillStyle='#fff';fitText(g,it.name||'—',it.x,1295,260,24,900,'center');}
  g.fillStyle='rgba(255,255,255,.65)';g.font='700 14px system-ui';g.textAlign='left';g.fillText(`STARTED  ${($('startDate').value||'—').trim()}`,62,1352);g.textAlign='right';g.fillText(`CARD DATE  ${($('printDate').value||'—').trim()}`,838,1352);
}
function drawBack(){const c=$('backCanvas'),g=c.getContext('2d'),p=TEAM[S.team];g.clearRect(0,0,c.width,c.height);drawBackdrop(g,p,'back');g.fillStyle=p.accent2;g.font='900 22px system-ui';g.textAlign='center';g.fillText('TRAINER CODE',450,84);g.fillStyle='#fff';fitText(g,($('trainerName').value||'TRAINER').trim(),450,145,720,48,950,'center');g.fillStyle=p.accent;g.font='900 20px system-ui';g.fillText(p.name.toUpperCase(),450,190);g.fillStyle='rgba(5,8,13,.78)';rr(g,145,245,610,650,28);g.fill();g.fillStyle='#fff';rr(g,240,310,420,420,24);g.fill();if(S.qrCrop)cover(g,S.qrCrop,260,330,380,380,12);else{g.fillStyle='#131a24';g.font='800 24px system-ui';g.textAlign='center';g.fillText('UPLOAD TRAINER CODE',450,505);g.fillStyle='#758195';g.font='700 17px system-ui';g.fillText('QR code will appear here',450,545);}g.fillStyle='#fff';g.font='950 36px ui-monospace,monospace';g.fillText(formatCode($('trainerCode').value)||'••••  ••••  ••••',450,790);g.fillStyle='rgba(255,255,255,.55)';g.font='800 15px system-ui';g.fillText('TRAINER CODE',450,830);g.fillStyle='rgba(5,8,13,.72)';rr(g,145,930,610,270,24);g.fill();const items=[['LEVEL',$('level').value,210,985],['BUDDY',$('buddy').value,480,985],['STARTED',$('startDate').value,210,1090],['TEAM',p.name,480,1090]];for(const [lab,valv,x,y] of items){g.textAlign='left';g.fillStyle='rgba(255,255,255,.56)';g.font='800 15px system-ui';g.fillText(lab,x,y);g.fillStyle='#fff';fitText(g,(valv||'—').trim(),x,y+38,250,27,900,'left');}g.fillStyle='rgba(255,255,255,.48)';g.font='700 14px system-ui';g.textAlign='center';g.fillText(`CARD DATE  ${($('printDate').value||'—').trim()}`,450,1318);}
function drawAll(){drawFront();drawBack();}

const formatCode=v=>{const d=(v||'').replace(/\D/g,'').slice(0,12);return d.replace(/(\d{4})(?=\d)/g,'$1  ').trim();};
const canvasFrom=img=>{const max=1800,s=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),c=document.createElement('canvas');c.width=Math.round(img.naturalWidth*s);c.height=Math.round(img.naturalHeight*s);c.getContext('2d',{willReadFrequently:true}).drawImage(img,0,0,c.width,c.height);return c;};
const qrCrop=(c,b)=>{if(!b)return null;const p=Math.max(b.width,b.height)*.12,x=Math.max(0,b.x-p),y=Math.max(0,b.y-p),w=Math.min(c.width-x,b.width+2*p),h=Math.min(c.height-y,b.height+2*p),side=Math.min(c.width,c.height,Math.max(w,h)),cx=x+w/2,cy=y+h/2,sx=Math.max(0,Math.min(c.width-side,cx-side/2)),sy=Math.max(0,Math.min(c.height-side,cy-side/2)),o=document.createElement('canvas');o.width=o.height=640;o.getContext('2d').drawImage(c,sx,sy,side,side,0,0,640,640);return o;};
const extractCode=t=>{let m=t.match(/\b\d{4}[\s-]+\d{4}[\s-]+\d{4}\b/);if(m)return m[0].replace(/\D/g,'');m=t.match(/(?:^|\D)(\d{12})(?:\D|$)/);if(m)return m[1];for(const line of t.split(/[\r\n]+/)){const d=line.replace(/\D/g,'');if(d.length===12)return d;}return'';};
async function detectQr(c){if('BarcodeDetector'in window)try{const d=new BarcodeDetector({formats:['qr_code']}),r=await d.detect(c);if(r.length)return{raw:r[0].rawValue||'',crop:qrCrop(c,r[0].boundingBox)}}catch(e){console.warn(e)}if(window.jsQR)try{const g=c.getContext('2d',{willReadFrequently:true}),im=g.getImageData(0,0,c.width,c.height),r=window.jsQR(im.data,c.width,c.height,{inversionAttempts:'attemptBoth'});if(r){const p=[r.location.topLeftCorner,r.location.topRightCorner,r.location.bottomLeftCorner,r.location.bottomRightCorner],x=Math.min(...p.map(q=>q.x)),X=Math.max(...p.map(q=>q.x)),y=Math.min(...p.map(q=>q.y)),Y=Math.max(...p.map(q=>q.y));return{raw:r.data||'',crop:qrCrop(c,{x,y,width:X-x,height:Y-y})}}}catch(e){console.warn(e)}return{raw:'',crop:null};}
async function scanCode(){if(!S.codeImage)return;$('codeStatus').textContent='Scanning…';try{const c=canvasFrom(S.codeImage),q=await detectQr(c);S.qrCrop=q.crop;let code=extractCode(q.raw);if(!code){for(const psm of ['6','11']){const r=await read(c,psm,'0123456789 -');code=extractCode(r.text);if(code)break;}}if(code){$('trainerCode').value=formatCode(code);$('codeState').textContent='Detected';$('codeState').className='ok';}else{$('codeState').textContent='Review';$('codeState').className='review';}$('qrStatus').textContent=S.qrCrop?'QR detected':'QR needs review';$('codeStatus').textContent=code&&S.qrCrop?'Ready':'Review';drawAll();}catch(e){console.error(e);$('codeStatus').textContent='Review';}}

async function handleBackground(kind,file){if(!file)return;try{const {img,url}=await loadFile(file);revoke(S.bgURLs[kind]);S.bgURLs[kind]=url;S.backgrounds[kind]=img;const prefix=kind==='shared'?'sharedBg':kind==='front'?'frontBg':'backBg';$(prefix+'Thumb').src=url;$(prefix+'Name').textContent=file.name;$(prefix+'SourceCard').classList.remove('hidden');drawAll();}catch(e){console.error(e);toast('Could not open that background image.');}}
function clearBackgrounds(){for(const k of ['shared','front','back']){revoke(S.bgURLs[k]);S.bgURLs[k]='';S.backgrounds[k]=null;const prefix=k==='shared'?'sharedBg':k==='front'?'frontBg':'backBg';$(prefix+'SourceCard')?.classList.add('hidden');const input=$(prefix+'Input');if(input)input.value='';}drawAll();toast('Custom backgrounds cleared.');}
function bindCrop(kind){const c=$(kind+'CropCanvas');c?.addEventListener('pointerdown',e=>pointerDown(kind,e));c?.addEventListener('pointermove',e=>pointerMove(kind,e));c?.addEventListener('pointerup',pointerUp);c?.addEventListener('pointercancel',pointerUp);$(kind+'ApplyCrop')?.addEventListener('click',()=>applyCrop(kind));}
function hardReset(){revoke(S.infoURL);revoke(S.codeURL);Object.values(S.urls).forEach(revoke);S.infoImage=null;S.infoURL='';S.codeImage=null;S.codeURL='';S.qrCrop=null;S.sources={trainer:null,buddy:null,looking:null,favorite:null};S.urls={trainer:'',buddy:'',looking:'',favorite:''};S.outputs={trainer:null,buddy:null,looking:null,favorite:null};S.crops={trainer:{cx:.5,cy:.44,w:.62,h:.72},buddy:{cx:.5,cy:.45,r:.31},looking:{cx:.5,cy:.5,r:.30},favorite:{cx:.5,cy:.5,r:.30}};S.frame={w:520,h:560};S.slotZoom={trainer:1,buddy:1,looking:1,favorite:1};S.slotUseFull={trainer:false,buddy:false,looking:false,favorite:false};for(const k of ['shared','front','back']){revoke(S.bgURLs[k]);S.bgURLs[k]='';S.backgrounds[k]=null;}['trainerName','level','buddy','caught','stops','xp','startDate','trainerCode','lookingName','favoriteName'].forEach(id=>{if($(id))$(id).value='';});['trainerName','level','buddy','caught','stops','xp','startDate'].forEach(id=>setState(id,'manual'));$('printDate').value=today();$('profileInput').value='';$('codeInput').value='';['trainer','buddy','looking','favorite'].forEach(k=>{const inp=$(k+'ShotInput');if(inp)inp.value='';$(k+'SourceCard')?.classList.add('hidden');$(k+'CropEmpty')?.classList.remove('hidden');const r=$(k+'Result');if(r)r.classList.add('hidden');const t=$(k+'ResultText');if(t)t.textContent='No crop yet.';const cv=$(k+'CropCanvas');if(cv){cv.width=1;cv.height=1;}});$('infoSourceCard').classList.add('hidden');$('codeSourceCard').classList.add('hidden');$('cardEmpty').classList.remove('hidden');$('ocrAgainBtn').disabled=true;$('rescanCodeBtn').disabled=true;$('saveBtn').disabled=true;$('trainerFrameW').value='520';$('trainerFrameH').value='560';$('trainerFrameWOut').textContent='520';$('trainerFrameHOut').textContent='560';S.showBack=false;$('cardFlipper').classList.remove('flipped');$('sidePill').textContent='Front';setTeam('valor',false);$('teamStatus').textContent='Waiting for screenshot';updateQuality();drawAll();}

$('profileInput').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const {img,url}=await loadFile(f);revoke(S.infoURL);S.infoImage=img;S.infoURL=url;$('infoThumb').src=url;$('infoName').textContent=f.name;$('infoMeta').textContent=meta(f);$('infoSourceCard').classList.remove('hidden');$('cardEmpty').classList.add('hidden');$('ocrAgainBtn').disabled=false;$('saveBtn').disabled=false;await scanInfo();}catch(err){console.error(err);toast('Could not open that information screenshot.');}});
$('ocrAgainBtn').addEventListener('click',scanInfo);
document.querySelectorAll('.team').forEach(b=>b.addEventListener('click',()=>setTeam(b.dataset.team,false)));
['trainer','buddy','looking','favorite'].forEach(kind=>{$(kind+'ShotInput')?.addEventListener('change',e=>handleImageKind(kind,e.target.files?.[0]));bindCrop(kind);});
['trainer','buddy','looking','favorite'].forEach(kind=>{const z=$(kind+'Zoom'),zo=$(kind+'ZoomOut'),full=$(kind+'UseFull');z?.addEventListener('input',()=>{S.slotZoom[kind]=+z.value;if(zo)zo.textContent=S.slotZoom[kind].toFixed(2)+'×';drawAll();});full?.addEventListener('change',()=>{S.slotUseFull[kind]=!!full.checked;drawAll();});});
$('sharedBgInput')?.addEventListener('change',e=>handleBackground('shared',e.target.files?.[0]));$('frontBgInput')?.addEventListener('change',e=>handleBackground('front',e.target.files?.[0]));$('backBgInput')?.addEventListener('change',e=>handleBackground('back',e.target.files?.[0]));$('clearBackgroundsBtn')?.addEventListener('click',clearBackgrounds);
$('trainerFrameW').addEventListener('input',e=>{S.frame.w=+e.target.value;$('trainerFrameWOut').textContent=e.target.value;drawFront();});
$('trainerFrameH').addEventListener('input',e=>{S.frame.h=+e.target.value;$('trainerFrameHOut').textContent=e.target.value;drawFront();});
['trainerName','level','buddy','caught','stops','xp','startDate','printDate','lookingName','favoriteName'].forEach(id=>$(id)?.addEventListener('input',()=>{if(['trainerName','level','buddy','caught','stops','xp','startDate'].includes(id))setState(id,'manual');updateQuality();drawAll();}));
$('codeInput').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const {img,url}=await loadFile(f);revoke(S.codeURL);S.codeImage=img;S.codeURL=url;$('codeThumb').src=url;$('codeName').textContent=f.name;$('codeMeta').textContent=meta(f);$('codeSourceCard').classList.remove('hidden');$('rescanCodeBtn').disabled=false;await scanCode();}catch(err){console.error(err);toast('Could not open that Trainer Code screenshot.');}});
$('rescanCodeBtn').addEventListener('click',scanCode);
$('trainerCode').addEventListener('input',()=>{ $('trainerCode').value=formatCode($('trainerCode').value);$('codeState').textContent='Manual';$('codeState').className='';drawBack();});
function flip(){S.showBack=!S.showBack;$('cardFlipper').classList.toggle('flipped',S.showBack);$('sidePill').textContent=S.showBack?'Back':'Front';$('saveBtn').querySelector('small').textContent=`${S.showBack?'Back':'Front'} · PNG`;}
$('flipBtn').addEventListener('click',flip);$('cardStage').addEventListener('click',flip);$('cardStage').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();flip();}});
$('saveBtn').addEventListener('click',()=>{drawAll();const c=S.showBack?$('backCanvas'):$('cardCanvas'),a=document.createElement('a'),name=($('trainerName').value||'trainer').replace(/\W+/g,'_');a.href=c.toDataURL('image/png');a.download=`${name}_${S.team}_trainer_card_${S.showBack?'back':'front'}_v28.png`;a.click();toast(`${S.showBack?'Back':'Front'} card saved.`);});
$('resetBtn').addEventListener('click',hardReset);
$('printDate').value=today();setTheme();hardReset();
})();
