(() => {
'use strict';
const $=id=>document.getElementById(id), kinds=['trainer','buddy','looking','favorite'];
const fresh=()=>({trainer:{cx:.5,cy:.44,w:.62,h:.72},buddy:{cx:.5,cy:.45,r:.31},looking:{cx:.5,cy:.5,r:.30},favorite:{cx:.5,cy:.5,r:.30}});
const state=fresh(), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function css(){if($('#tc32css'))return;const s=document.createElement('style');s.id='tc32css';s.textContent=`
.cropCanvasWrap{position:relative!important;touch-action:pan-y pinch-zoom!important;overscroll-behavior:auto!important}.cropCanvasWrap canvas{pointer-events:none!important;touch-action:pan-y pinch-zoom!important}.cropCanvasWrap.cropEditing{touch-action:none!important;outline:2px solid var(--accent);outline-offset:3px;border-radius:14px}.cropCanvasWrap.cropEditing canvas{pointer-events:none!important;touch-action:none!important}.tcLayer{position:absolute;inset:0;z-index:30;display:none;pointer-events:none}.cropEditing .tcLayer{display:block}.tcMove{position:absolute;transform:translate(-50%,-50%);pointer-events:auto;touch-action:none;border:2px dashed rgba(255,255,255,.7);background:rgba(255,255,255,.025);box-sizing:border-box}.tcMove.rect{border-radius:10px}.tcMove.circle{border-radius:50%}.tcMove:after{content:'DRAG TO MOVE';position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);padding:5px 8px;border-radius:999px;background:rgba(5,8,13,.8);color:#fff;font:900 9px/1 system-ui;white-space:nowrap;pointer-events:none}.tcH{position:absolute;z-index:35;width:64px;height:64px;margin:-32px 0 0 -32px;border:3px solid #fff;border-radius:50%;background:rgba(5,8,13,.97);color:#fff;display:grid;place-items:center;font:900 23px/1 system-ui;box-shadow:0 4px 18px rgba(0,0,0,.7),0 0 0 5px rgba(0,0,0,.25);pointer-events:auto;touch-action:none;user-select:none}.tcH.big{width:70px;height:70px;margin:-35px 0 0 -35px}.tcH:active{background:var(--accent);color:#080b10}.tcBadge{position:absolute;z-index:36;top:8px;left:8px;display:none;padding:6px 9px;border:1px solid var(--accent);border-radius:999px;background:rgba(5,8,13,.92);color:var(--accent2);font-size:9px;font-weight:900;pointer-events:none}.cropEditing .tcBadge{display:block}.cropModeBtn{min-height:50px!important}.cropAdjustBlock button{min-height:48px}
`;document.head.appendChild(s)}
function send(c,t,id,x,y){const ev=new PointerEvent(t,{bubbles:true,cancelable:true,pointerId:id,pointerType:'touch',isPrimary:true,clientX:x,clientY:y,button:0,buttons:t==='pointerup'?0:1,pressure:t==='pointerup'?0:.5});if(t==='pointerdown'&&c.setPointerCapture){const old=c.setPointerCapture;try{c.setPointerCapture=()=>{};c.dispatchEvent(ev)}finally{c.setPointerCapture=old}}else c.dispatchEvent(ev)}
function pt(c,x,y){const r=c.getBoundingClientRect();return{x:r.left+x*r.width,y:r.top+y*r.height}}
function geom(k){const c=$(k+'CropCanvas'),s=state[k];if(k==='trainer')return{cx:s.cx,cy:s.cy,w:s.w,h:s.h};const m=Math.min(c.width||1,c.height||1);return{cx:s.cx,cy:s.cy,rx:s.r*m/(c.width||1),ry:s.r*m/(c.height||1)}}
function paint(k){const g=geom(k),m=$(k+'Move');if(!g||!m)return;if(k==='trainer'){m.style.cssText+=`;left:${g.cx*100}%;top:${g.cy*100}%;width:${g.w*100}%;height:${g.h*100}%`;const w=$(k+'W'),h=$(k+'H'),b=$(k+'B');w.style.left=`${(g.cx+g.w/2)*100}%`;w.style.top=`${g.cy*100}%`;h.style.left=`${g.cx*100}%`;h.style.top=`${(g.cy+g.h/2)*100}%`;b.style.left=`${(g.cx+g.w/2)*100}%`;b.style.top=`${(g.cy+g.h/2)*100}%`}else{m.style.cssText+=`;left:${g.cx*100}%;top:${g.cy*100}%;width:${g.rx*200}%;height:${g.ry*200}%`;const r=$(k+'R');r.style.left=`${(g.cx+g.rx)*100}%`;r.style.top=`${g.cy*100}%`}}
function anchor(k,mode){const c=$(k+'CropCanvas'),s=state[k];if(k==='trainer'){if(mode==='move')return pt(c,s.cx,s.cy);if(mode==='w')return pt(c,s.cx+s.w/2,s.cy);if(mode==='h')return pt(c,s.cx,s.cy+s.h/2);return pt(c,s.cx+s.w/2,s.cy+s.h/2)}const m=Math.min(c.width||1,c.height||1),rx=s.r*m/(c.width||1);return mode==='move'?pt(c,s.cx,s.cy):pt(c,s.cx+rx,s.cy)}
function local(k,mode,start,dx,dy,rect,c){const s=state[k];if(k==='trainer'){if(mode==='move'){s.cx=clamp(start.cx+dx/rect.width,start.w/2,1-start.w/2);s.cy=clamp(start.cy+dy/rect.height,start.h/2,1-start.h/2)}else{if(mode==='w'||mode==='both')s.w=clamp(start.w+2*dx/rect.width,.18,.96);if(mode==='h'||mode==='both')s.h=clamp(start.h+2*dy/rect.height,.20,.96);s.cx=clamp(start.cx,s.w/2,1-s.w/2);s.cy=clamp(start.cy,s.h/2,1-s.h/2)}}else{const m=Math.min(c.width||1,c.height||1);if(mode==='move'){s.cx=start.cx+dx/rect.width;s.cy=start.cy+dy/rect.height;const rx=s.r*m/(c.width||1),ry=s.r*m/(c.height||1);s.cx=clamp(s.cx,rx,1-rx);s.cy=clamp(s.cy,ry,1-ry)}else{const ix=dx*(c.width||1)/rect.width;s.r=clamp(start.r+ix/m,.08,.48);const rx=s.r*m/(c.width||1),ry=s.r*m/(c.height||1);s.cx=clamp(start.cx,rx,1-rx);s.cy=clamp(start.cy,ry,1-ry)}}}
function drag(el,k,mode){el.addEventListener('pointerdown',e=>{const c=$(k+'CropCanvas'),wrap=c?.closest('.cropCanvasWrap');if(!c||!wrap?.classList.contains('cropEditing')||c.width<=1)return;e.preventDefault();e.stopPropagation();const id=e.pointerId||77,rect=c.getBoundingClientRect(),start={...state[k]},a=anchor(k,mode),sx=e.clientX,sy=e.clientY;el.setPointerCapture?.(e.pointerId);send(c,'pointerdown',id,a.x,a.y);const mv=q=>{const dx=q.clientX-sx,dy=q.clientY-sy;local(k,mode,start,dx,dy,rect,c);paint(k);send(c,'pointermove',id,a.x+dx,a.y+dy);q.preventDefault()};const up=q=>{el.removeEventListener('pointermove',mv);el.removeEventListener('pointerup',up);el.removeEventListener('pointercancel',up);const dx=(q.clientX??sx)-sx,dy=(q.clientY??sy)-sy;send(c,'pointerup',id,a.x+dx,a.y+dy);requestAnimationFrame(()=>$(k+'ApplyCrop')?.click());q.preventDefault()};el.addEventListener('pointermove',mv);el.addEventListener('pointerup',up);el.addEventListener('pointercancel',up)})}
function mode(k,on){const c=$(k+'CropCanvas'),w=c?.closest('.cropCanvasWrap'),b=$(k+'Mode'),h=$(k+'Help');if(!c||!w||!b)return;if(on&&c.width<=1){h.innerHTML='<strong>Upload a screenshot first.</strong>';return}kinds.forEach(x=>{if(x!==k&&$(x+'CropCanvas')?.closest('.cropCanvasWrap')?.classList.contains('cropEditing'))mode(x,false)});w.classList.toggle('cropEditing',on);b.classList.toggle('active',on);b.textContent=on?'Done adjusting':'Adjust crop';b.setAttribute('aria-pressed',on?'true':'false');h.innerHTML=on?'<strong>Adjust mode:</strong> drag the outlined crop to move it. Drag the large round handles to resize.':'<strong>Scroll mode:</strong> swipe directly over the screenshot to scroll the page.';paint(k)}
function layer(k){const c=$(k+'CropCanvas'),w=c?.closest('.cropCanvasWrap');if(!c||!w)return;const badge=document.createElement('div');badge.className='tcBadge';badge.textContent='ADJUST MODE';w.appendChild(badge);const l=document.createElement('div');l.className='tcLayer';l.id=k+'Layer';if(k==='trainer')l.innerHTML=`<div id="${k}Move" class="tcMove rect"></div><button id="${k}W" class="tcH" type="button">↔</button><button id="${k}H" class="tcH" type="button">↕</button><button id="${k}B" class="tcH big" type="button">↘</button>`;else l.innerHTML=`<div id="${k}Move" class="tcMove circle"></div><button id="${k}R" class="tcH big" type="button">↔</button>`;w.appendChild(l);drag($(k+'Move'),k,'move');if(k==='trainer'){drag($(k+'W'),k,'w');drag($(k+'H'),k,'h');drag($(k+'B'),k,'both')}else drag($(k+'R'),k,'r');paint(k)}
function step(k,a){const c=$(k+'CropCanvas');if(!c||c.width<=1)return;const r=c.getBoundingClientRect(),d=.045;let modeName='move',dx=0,dy=0;if(a==='left')dx=-d*r.width;if(a==='right')dx=d*r.width;if(a==='up')dy=-d*r.height;if(a==='down')dy=d*r.height;if(k==='trainer'){if(a==='wider'){modeName='w';dx=d*r.width}if(a==='narrower'){modeName='w';dx=-d*r.width}if(a==='taller'){modeName='h';dy=d*r.height}if(a==='shorter'){modeName='h';dy=-d*r.height}}else if(a==='larger'||a==='smaller'){modeName='r';dx=(a==='larger'?d:-d)*r.width}const st={...state[k]},p=anchor(k,modeName),id=88;send(c,'pointerdown',id,p.x,p.y);local(k,modeName,st,dx,dy,r,c);paint(k);send(c,'pointermove',id,p.x+dx,p.y+dy);send(c,'pointerup',id,p.x+dx,p.y+dy);requestAnimationFrame(()=>$(k+'ApplyCrop')?.click())}
function controls(k){const c=$(k+'CropCanvas'),w=c?.closest('.cropCanvasWrap');if(!c||!w)return;const bar=document.createElement('div');bar.className='cropModeBar';bar.innerHTML=`<button id="${k}Mode" class="cropModeBtn" type="button" aria-pressed="false">Adjust crop</button><div id="${k}Help" class="cropModeHelp"><strong>Scroll mode:</strong> swipe directly over the screenshot to scroll the page.</div>`;w.insertAdjacentElement('afterend',bar);$(k+'Mode').onclick=()=>mode(k,!w.classList.contains('cropEditing'));const box=document.createElement('div');box.className='cropAdjustBlock';const sizes=k==='trainer'?'<button data-a="narrower">Narrower</button><button data-a="wider">Wider</button><button data-a="shorter">Shorter</button><button data-a="taller">Taller</button>':'<button data-a="smaller">Smaller</button><button data-a="larger">Larger</button>';box.innerHTML=`<div class="cropAdjustHead"><b>Fine adjustment</b><span>Use these for small precise changes.</span></div><div class="cropAdjustGrid"><div class="movePad"><button data-a="up">↑</button><button data-a="left">←</button><button class="center" disabled>MOVE</button><button data-a="right">→</button><button data-a="down">↓</button></div><div class="sizePad">${sizes}</div></div><div class="cropScrollNote">Tap Adjust crop for the large drag handles. Tap Done adjusting to restore swipe scrolling.</div>`;bar.insertAdjacentElement('afterend',box);box.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>step(k,b.dataset.a));$(k+'ShotInput')?.addEventListener('change',()=>{Object.assign(state[k],fresh()[k]);mode(k,false);setTimeout(()=>paint(k),100)})}
function init(){css();kinds.forEach(k=>{controls(k);layer(k)});$('resetBtn')?.addEventListener('click',()=>{const d=fresh();kinds.forEach(k=>{Object.assign(state[k],d[k]);mode(k,false);paint(k)})})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();