(() => {
'use strict';
const $=id=>document.getElementById(id);
const kinds=['trainer','buddy','looking','favorite'];
const state={trainer:{cx:.5,cy:.44,w:.62,h:.72},buddy:{cx:.5,cy:.45,r:.31},looking:{cx:.5,cy:.5,r:.30},favorite:{cx:.5,cy:.5,r:.30}};
const defaults=()=>({trainer:{cx:.5,cy:.44,w:.62,h:.72},buddy:{cx:.5,cy:.45,r:.31},looking:{cx:.5,cy:.5,r:.30},favorite:{cx:.5,cy:.5,r:.30}});
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function readyImage(img){return !!(img&&img.src&&img.complete&&img.naturalWidth>0&&img.naturalHeight>0);}
function shown(el){return !!(el&&!el.classList.contains('hidden'));}
function chosenDomImage(kind){const full=$(kind+'UseFull'),src=$(kind+'SourceThumb'),srcCard=$(kind+'SourceCard'),result=$(kind+'Result');const sourceOK=readyImage(src)&&shown(srcCard),resultOK=readyImage(result)&&shown(result);if(full?.checked)return sourceOK?src:(resultOK?result:null);return resultOK?result:(sourceOK?src:null);}
function zoomFor(kind){return Math.max(.25,Math.min(2,Number($(kind+'Zoom')?.value||1)));}
function cssAccent(){return getComputedStyle(document.documentElement).getPropertyValue('--accent2').trim()||'#fff';}
function roundedPath(g,x,y,w,h,r){g.beginPath();g.roundRect(x,y,w,h,r);}
function drawCover(g,img,w,h,zoom){if(!readyImage(img))return false;const iw=img.naturalWidth,ih=img.naturalHeight,base=Math.max(w/iw,h/ih),sc=base*zoom,dw=iw*sc,dh=ih*sc;g.drawImage(img,(w-dw)/2,(h-dh)/2,dw,dh);return true;}

function renderSlot(kind){const canvas=$(kind+'SlotPreview'),shape=$(kind+'SlotPreviewShape');if(!canvas||!shape)return;const trainer=kind==='trainer';let w=420,h=420;if(trainer){const fw=Math.max(1,Number($('trainerFrameW')?.value||520)),fh=Math.max(1,Number($('trainerFrameH')?.value||560));h=Math.round(w*fh/fw);shape.style.aspectRatio=`${fw} / ${fh}`;}canvas.width=w;canvas.height=h;const g=canvas.getContext('2d');g.clearRect(0,0,w,h);g.fillStyle='#05080d';g.fillRect(0,0,w,h);g.save();if(trainer){roundedPath(g,0,0,w,h,Math.max(14,w*.045));g.clip();}else{g.beginPath();g.arc(w/2,h/2,Math.min(w,h)/2,0,Math.PI*2);g.clip();}const img=chosenDomImage(kind),ok=drawCover(g,img,w,h,zoomFor(kind));if(!ok){g.fillStyle='#0b1119';g.fillRect(0,0,w,h);g.fillStyle='rgba(255,255,255,.45)';g.textAlign='center';g.textBaseline='middle';g.font='800 22px system-ui';g.fillText('UPLOAD IMAGE',w/2,h/2);}g.restore();g.strokeStyle=cssAccent();g.lineWidth=Math.max(4,w*.012);if(trainer){roundedPath(g,g.lineWidth/2,g.lineWidth/2,w-g.lineWidth,h-g.lineWidth,Math.max(14,w*.045));g.stroke();}else{g.beginPath();g.arc(w/2,h/2,Math.min(w,h)/2-g.lineWidth/2,0,Math.PI*2);g.stroke();}const z=$(kind+'SlotZoomText');if(z)z.textContent=`${zoomFor(kind).toFixed(2)}×`;}
function buildSlotPreview(kind){const input=$(kind+'ShotInput'),host=input?.closest('.cropCard,.optionalCard');if(!host||$(kind+'SlotPreview'))return;const block=document.createElement('div');block.className='slotPreviewBlock';block.innerHTML=`<div class="slotPreviewHead"><b>Live card-slot preview</b><span id="${kind}SlotZoomText">1.00×</span></div><div class="slotPreviewStage"><div id="${kind}SlotPreviewShape" class="slotPreviewShape ${kind==='trainer'?'trainer':'circle'}"><canvas id="${kind}SlotPreview"></canvas></div></div><div class="slotPreviewFoot">This matches the crop/zoom used on the finished card.</div>`;const ranges=host.querySelector('.rangeGrid');if(ranges)host.insertBefore(block,ranges);else host.appendChild(block);const rerender=()=>requestAnimationFrame(()=>renderSlot(kind));$(kind+'Zoom')?.addEventListener('input',rerender);$(kind+'UseFull')?.addEventListener('change',rerender);$(kind+'Result')?.addEventListener('load',rerender);$(kind+'SourceThumb')?.addEventListener('load',rerender);if(kind==='trainer'){$('trainerFrameW')?.addEventListener('input',rerender);$('trainerFrameH')?.addEventListener('input',rerender);}rerender();}

function sendPointer(canvas,type,pointerId,clientX,clientY){const init={bubbles:true,cancelable:true,pointerId,pointerType:'touch',isPrimary:true,clientX,clientY,button:0,buttons:type==='pointerup'?0:1,pressure:type==='pointerup'?0:.5};const ev=new PointerEvent(type,init);if(type==='pointerdown'&&canvas.setPointerCapture){const old=canvas.setPointerCapture;try{canvas.setPointerCapture=()=>{};canvas.dispatchEvent(ev);}finally{canvas.setPointerCapture=old;}}else canvas.dispatchEvent(ev);}
function canvasClient(canvas,x,y){const r=canvas.getBoundingClientRect();return{x:r.left+x/canvas.width*r.width,y:r.top+y/canvas.height*r.height};}
function gesture(kind,action){const canvas=$(kind+'CropCanvas');if(!canvas||canvas.width<=1||canvas.height<=1)return;const s=state[kind],cw=canvas.width,ch=canvas.height,min=Math.min(cw,ch),step=.045,pid=31;let sx,sy,tx,ty;if(kind==='trainer'){const x=(s.cx-s.w/2)*cw,y=(s.cy-s.h/2)*ch,w=s.w*cw,h=s.h*ch;if(action==='left'||action==='right'||action==='up'||action==='down'){sx=s.cx*cw;sy=s.cy*ch;tx=sx+(action==='left'?-step*cw:action==='right'?step*cw:0);ty=sy+(action==='up'?-step*ch:action==='down'?step*ch:0);s.cx=clamp(s.cx+(tx-sx)/cw,s.w/2,1-s.w/2);s.cy=clamp(s.cy+(ty-sy)/ch,s.h/2,1-s.h/2);}else if(action==='wider'||action==='narrower'){sx=x+w;sy=y+h/2;tx=sx+(action==='wider'?step*cw:-step*cw);ty=sy;s.w=clamp(s.w+2*(tx-sx)/cw,.18,.96);s.cx=clamp(s.cx,s.w/2,1-s.w/2);}else if(action==='taller'||action==='shorter'){sx=x+w/2;sy=y+h;tx=sx;ty=sy+(action==='taller'?step*ch:-step*ch);s.h=clamp(s.h+2*(ty-sy)/ch,.20,.96);s.cy=clamp(s.cy,s.h/2,1-s.h/2);}else return;}else{const r=s.r*min,cx=s.cx*cw,cy=s.cy*ch;if(action==='left'||action==='right'||action==='up'||action==='down'){sx=cx;sy=cy;tx=sx+(action==='left'?-step*cw:action==='right'?step*cw:0);ty=sy+(action==='up'?-step*ch:action==='down'?step*ch:0);s.cx=clamp(s.cx+(tx-sx)/cw,.05,.95);s.cy=clamp(s.cy+(ty-sy)/ch,.05,.95);const rx=s.r*min/cw,ry=s.r*min/ch;s.cx=clamp(s.cx,rx,1-rx);s.cy=clamp(s.cy,ry,1-ry);}else if(action==='larger'||action==='smaller'){sx=cx+r;sy=cy;tx=sx+(action==='larger'?step*min:-step*min);ty=sy;s.r=clamp(s.r+(tx-sx)/min,.08,.48);const rx=s.r*min/cw,ry=s.r*min/ch;s.cx=clamp(s.cx,rx,1-rx);s.cy=clamp(s.cy,ry,1-ry);}else return;}const a=canvasClient(canvas,sx,sy),b=canvasClient(canvas,tx,ty);sendPointer(canvas,'pointerdown',pid,a.x,a.y);sendPointer(canvas,'pointermove',pid,b.x,b.y);sendPointer(canvas,'pointerup',pid,b.x,b.y);requestAnimationFrame(()=>{$(kind+'ApplyCrop')?.click();renderSlot(kind);});}
function buildAdjustControls(kind){const canvas=$(kind+'CropCanvas'),wrap=canvas?.closest('.cropCanvasWrap');if(!canvas||!wrap||$(kind+'CropAdjust'))return;const block=document.createElement('div');block.id=kind+'CropAdjust';block.className='cropAdjustBlock';const sizeButtons=kind==='trainer'?'<button data-act="narrower">Narrower</button><button data-act="wider">Wider</button><button data-act="shorter">Shorter</button><button data-act="taller">Taller</button>':'<button data-act="smaller">Smaller</button><button data-act="larger">Larger</button>';block.innerHTML=`<div class="cropAdjustHead"><b>Fine adjustment</b><span>Optional buttons for small moves and size changes.</span></div><div class="cropAdjustGrid"><div class="movePad"><button data-act="up" aria-label="Move crop up">↑</button><button data-act="left" aria-label="Move crop left">←</button><button class="center" type="button" disabled>MOVE</button><button data-act="right" aria-label="Move crop right">→</button><button data-act="down" aria-label="Move crop down">↓</button></div><div class="sizePad">${sizeButtons}</div></div><div class="cropScrollNote">Normal mode: swipe on the screenshot to scroll. Adjust mode: drag directly on the crop.</div>`;wrap.insertAdjacentElement('afterend',block);block.querySelectorAll('button[data-act]').forEach(b=>b.addEventListener('click',()=>gesture(kind,b.dataset.act)));}

function setCropMode(kind,on){const canvas=$(kind+'CropCanvas'),wrap=canvas?.closest('.cropCanvasWrap'),btn=$(kind+'CropModeBtn'),help=$(kind+'CropModeHelp');if(!canvas||!wrap||!btn)return;if(on&&canvas.width<=1){if(help)help.innerHTML='<strong>Upload a screenshot first.</strong>';return;}wrap.classList.toggle('cropEditing',on);btn.classList.toggle('active',on);btn.setAttribute('aria-pressed',on?'true':'false');btn.textContent=on?'Done adjusting':'Adjust crop';if(help)help.innerHTML=on?'<strong>Adjust mode:</strong> drag inside the crop to move it; drag the white handle to resize.':'<strong>Scroll mode:</strong> swipe directly over the screenshot to move up or down the page.';}
function buildCropMode(kind){const canvas=$(kind+'CropCanvas'),wrap=canvas?.closest('.cropCanvasWrap');if(!canvas||!wrap||$(kind+'CropModeBtn'))return;const badge=document.createElement('div');badge.className='cropEditBadge';badge.textContent='ADJUSTING CROP';wrap.appendChild(badge);const bar=document.createElement('div');bar.className='cropModeBar';bar.innerHTML=`<button id="${kind}CropModeBtn" class="cropModeBtn" type="button" aria-pressed="false">Adjust crop</button><div id="${kind}CropModeHelp" class="cropModeHelp"><strong>Scroll mode:</strong> swipe directly over the screenshot to move up or down the page.</div>`;wrap.insertAdjacentElement('afterend',bar);$(kind+'CropModeBtn').addEventListener('click',()=>setCropMode(kind,!wrap.classList.contains('cropEditing')));canvas.addEventListener('pointerup',()=>{if(wrap.classList.contains('cropEditing'))requestAnimationFrame(()=>{$(kind+'ApplyCrop')?.click();renderSlot(kind);});});canvas.addEventListener('pointercancel',()=>{if(wrap.classList.contains('cropEditing'))requestAnimationFrame(()=>{$(kind+'ApplyCrop')?.click();renderSlot(kind);});});$(kind+'ShotInput')?.addEventListener('change',()=>setCropMode(kind,false));}

function renderBackgroundPreview(kind){const prefix=kind==='shared'?'sharedBg':kind==='front'?'frontBg':'backBg',canvas=$(prefix+'CardPreview'),img=$(prefix+'Thumb'),card=$(prefix+'SourceCard');if(!canvas)return;canvas.width=180;canvas.height=280;const g=canvas.getContext('2d');g.fillStyle='#080b10';g.fillRect(0,0,180,280);if(readyImage(img)&&shown(card))drawCover(g,img,180,280,1);else{g.fillStyle='rgba(255,255,255,.38)';g.textAlign='center';g.textBaseline='middle';g.font='800 12px system-ui';g.fillText('NO CUSTOM IMAGE',90,140);}g.strokeStyle=cssAccent();g.lineWidth=3;roundedPath(g,2,2,176,276,12);g.stroke();}
function buildBackgroundPreview(kind){const prefix=kind==='shared'?'sharedBg':kind==='front'?'frontBg':'backBg',input=$(prefix+'Input'),host=input?.closest('.backgroundCard');if(!host||$(prefix+'CardPreview'))return;const b=document.createElement('div');b.className='slotPreviewBlock';b.innerHTML=`<div class="slotPreviewHead"><b>Card background preview</b><span>9:14</span></div><div class="slotPreviewStage"><div class="slotPreviewShape trainer" style="width:126px;aspect-ratio:9/14"><canvas id="${prefix}CardPreview"></canvas></div></div><div class="slotPreviewFoot">Shows the same center-cover crop used behind the finished card.</div>`;host.appendChild(b);const rerender=()=>requestAnimationFrame(()=>renderBackgroundPreview(kind));$(prefix+'Thumb')?.addEventListener('load',rerender);rerender();}
function installSave(){const btn=$('saveBtn');if(!btn)return;btn.addEventListener('click',e=>{e.stopImmediatePropagation();const side=($('sidePill')?.textContent||'Front').toLowerCase()==='back'?'back':'front',canvas=side==='back'?$('backCanvas'):$('cardCanvas');if(!canvas)return;const trainer=($('trainerName')?.value||'trainer').replace(/\W+/g,'_'),team=document.querySelector('.team.active')?.dataset.team||'team',a=document.createElement('a');a.href=canvas.toDataURL('image/png');a.download=`${trainer}_${team}_trainer_card_${side}_mobilefix.png`;a.click();},true);}
function resetLocalState(){const d=defaults();for(const k of kinds)Object.assign(state[k],d[k]);}
function init(){kinds.forEach(kind=>{buildCropMode(kind);buildAdjustControls(kind);buildSlotPreview(kind);});['shared','front','back'].forEach(buildBackgroundPreview);$('resetBtn')?.addEventListener('click',()=>{resetLocalState();kinds.forEach(kind=>{setCropMode(kind,false);renderSlot(kind);});});installSave();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
